.TH "Generator_Module" 3 "Fri Dec 15 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Generator_Module \- Generator module controller
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGenerator\fP"
.br
.RI "<>  "
.in -1c
.SH "Detailed Description"
.PP 



.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
