.TH "GlobalObjects" 3 "Mon Dec 4 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GlobalObjects
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Object ^ \fBpMotShift\fP = nullptr"
.br
.RI "Pointer to the Shift Motor\&. "
.ti -1c
.RI "static int \fBmonitor_X0\fP"
.br
.RI "Pointer to the Monitor X0 position\&. "
.ti -1c
.RI "static int \fBmonitor_Y0\fP"
.br
.RI "Pointer to the Monitor Y0 position\&. "
.ti -1c
.RI "static System::String ^ \fBapplicationResourcePath\fP"
.br
.RI "This is the current application resource path\&. "
.ti -1c
.RI "static Object ^ \fBpIdleForm\fP = nullptr"
.br
.RI "Pointer to the \fBIdleForm\fP\&. "
.ti -1c
.RI "static Object ^ \fBpOperatingForm\fP = nullptr"
.br
.RI "Pointer to the \fBOperatingForm\fP\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "System::String ^ GlobalObjects::applicationResourcePath\fC [static]\fP"

.PP
This is the current application resource path\&. 
.SS "int GlobalObjects::monitor_X0\fC [static]\fP"

.PP
Pointer to the Monitor X0 position\&. 
.SS "int GlobalObjects::monitor_Y0\fC [static]\fP"

.PP
Pointer to the Monitor Y0 position\&. 
.SS "Object ^ GlobalObjects::pIdleForm = nullptr\fC [static]\fP"

.PP
Pointer to the \fBIdleForm\fP\&. 
.SS "Object ^ GlobalObjects::pMotShift = nullptr\fC [static]\fP"

.PP
Pointer to the Shift Motor\&. 
.SS "Object ^ GlobalObjects::pOperatingForm = nullptr\fC [static]\fP"

.PP
Pointer to the \fBOperatingForm\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
