.TH "IDLESTATUS::batteryStatus" 3 "Wed May 29 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IDLESTATUS::batteryStatus
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBbattena\fP"
.br
.ti -1c
.RI "bool \fBbattery_alarm\fP"
.br
.ti -1c
.RI "unsigned char \fBvbatt1\fP"
.br
.ti -1c
.RI "unsigned char \fBvbatt2\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool IDLESTATUS::batteryStatus::battena"

.SS "bool IDLESTATUS::batteryStatus::battery_alarm"

.SS "unsigned char IDLESTATUS::batteryStatus::vbatt1"

.SS "unsigned char IDLESTATUS::batteryStatus::vbatt2"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
