.TH "OperatingMode_Section" 3 "Wed May 29 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperatingMode_Section \- Operating Mode Modules
.PP
 \- This section groups all the modules controlling the system operating modes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBStartup Module\fP"
.br
.RI "This module implements the Workflow and GUI to handle the system startup workflow\&. "
.in -1c
.SH "Detailed Description"
.PP 
This section groups all the modules controlling the system operating modes\&. 

The system operations are dived in a subset of operating modes:
.IP "\(bu" 2
Startup Mode: the initial status after system power on;
.IP "\(bu" 2
Idle Mode: the system idle mode management;
.IP "\(bu" 2
Operative Mode: the system operating mode management;
.IP "\(bu" 2
Service Mode: the system service mode management;
.PP
.PP
Every Operating mode is associated to a given graphical GUI and a given functional workflow\&.
.PP
See to the related Operating Mode sections for details\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
