.TH "PCB304" 3 "Wed May 29 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCB304
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PCB304\&.h>\fP
.PP
Inherits \fBCanDeviceProtocol\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBStatusRegisters\fP { \fBSYSTEM_STATUS_REGISTER\fP = 0 }"
.br
.RI "This is the Device STATUS Register implementation  "
.ti -1c
.RI "enum class \fBDataRegisters\fP { \fBDISPLAY_DATA_REGISTER\fP = 0, \fBGRID_DATA_REGISTER\fP }"
.br
.RI "This is the Device DATA Register implementation  "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPCB304\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBisMagnifierDeviceDetected\fP (void)"
.br
.RI "This function returns the presence of the magnifier device "
.ti -1c
.RI "static System::String ^ \fBgetMagnifierfactorString\fP (void)"
.br
.ti -1c
.RI "static bool \fBsetGridOnField\fP (bool wait_completion)"
.br
.ti -1c
.RI "static bool \fBsetGridOffField\fP (bool wait_completion)"
.br
.ti -1c
.RI "static void \fBsynchGridWithGenerator\fP (bool status)"
.br
.RI "This function activates/deactivates the grid synchronizatio with the generator\&. "
.ti -1c
.RI "static bool \fBisGridOnFieldReady\fP (void)"
.br
.RI "This function returns true if the Grid is correctly positioned in Field\&. "
.ti -1c
.RI "static bool \fBisGridOffFieldReady\fP (void)"
.br
.ti -1c
.RI "static bool \fBisGridSynchReady\fP (void)"
.br
.RI "If the grid has been set to \fBGenerator\fP Synch, the function returns true when the grid is ready to start\&. "
.ti -1c
.RI "static bool \fBisError\fP (void)"
.br
.ti -1c
.RI "static void \fBsetDisplay\fP (bool on_off)"
.br
.ti -1c
.RI "static void \fBsetDisplay\fP (short val, unsigned char decimals, bool blink, unsigned char intensity)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPCB304\fP ^ \fBdevice\fP = gcnew \fBPCB304\fP()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBrunningLoop\fP (void) override"
.br
.RI "This routine shall be overridden by the subclass module in order to inplement the specific module features\&. "
.ti -1c
.RI "void \fBdemoLoop\fP (void) override"
.br
.RI "This routine shall be overridden by the subclass module in order to implement the simulated features\&. "
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static bool \fBmagnifier_device_detected\fP = false"
.br
.RI "Is set if the Magnifier device has been detected\&. "
.ti -1c
.RI "static System::String ^ \fBmagnifier_factor_string\fP = '1\&.0'"
.br
.RI "This is the current magnification factor detected in string format\&. "
.ti -1c
.RI "static bool \fBgrid_on_field\fP = false"
.br
.RI "This is the status of the current grid position\&. "
.ti -1c
.RI "static bool \fBgrid_on_field_ready\fP = false"
.br
.RI "This flag stands for grid correctly positioned in Field\&. "
.ti -1c
.RI "static bool \fBgrid_off_field_ready\fP = false"
.br
.RI "This flag stands for grid correctly positioned out of Field\&. "
.ti -1c
.RI "static bool \fBsynch_grid\fP = false"
.br
.RI "This flag set the current synch status\&. "
.ti -1c
.RI "static bool \fBgrid_sync_ready\fP = false"
.br
.RI "This flag stands for grid ready to be activated by the generator\&. "
.ti -1c
.RI "static bool \fBerror\fP = false"
.br
.RI "The 2D grid is in error condition\&. "
.ti -1c
.RI "static bool \fBdisplay_on\fP = false"
.br
.ti -1c
.RI "static bool \fBdisplay_blink\fP = false"
.br
.ti -1c
.RI "static short \fBdisplay_val\fP = 0"
.br
.ti -1c
.RI "static unsigned char \fBdisplay_decimals\fP = 0"
.br
.ti -1c
.RI "static unsigned char \fBdisplay_intensity\fP = 0"
.br
.ti -1c
.RI "static \fBRegister\fP ^ \fBdisplay_data_register\fP = gcnew \fBRegister\fP()"
.br
.ti -1c
.RI "static \fBRegister\fP ^ \fBgrid_data_register\fP = gcnew \fBRegister\fP()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Enumeration Documentation"
.PP 
.SS "enum class \fBPCB304::DataRegisters\fP\fC [strong]\fP"

.PP
This is the Device DATA Register implementation  
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDISPLAY_DATA_REGISTER \fP\fP
.TP
\fB\fIGRID_DATA_REGISTER \fP\fP

.PP
.RS 4
This is the Display Data register index 
.RE
.PP
This is the control of the Grid status 
.SS "enum class \fBPCB304::StatusRegisters\fP\fC [strong]\fP"

.PP
This is the Device STATUS Register implementation  
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISYSTEM_STATUS_REGISTER \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PCB304::PCB304 ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void PCB304::demoLoop (void)\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
This routine shall be overridden by the subclass module in order to implement the simulated features\&. 
.PP
Reimplemented from \fBCanDeviceProtocol\fP\&.
.SS "static System::String ^ PCB304::getMagnifierfactorString (void)\fC [inline]\fP, \fC [static]\fP"

.SS "static bool PCB304::isError (void)\fC [inline]\fP, \fC [static]\fP"

.SS "static bool PCB304::isGridOffFieldReady (void)\fC [inline]\fP, \fC [static]\fP"

.SS "static bool PCB304::isGridOnFieldReady (void)\fC [inline]\fP, \fC [static]\fP"

.PP
This function returns true if the Grid is correctly positioned in Field\&. 
.PP
\fBReturns\fP
.RS 4
True if the Grid is in field
.RE
.PP

.SS "static bool PCB304::isGridSynchReady (void)\fC [inline]\fP, \fC [static]\fP"

.PP
If the grid has been set to \fBGenerator\fP Synch, the function returns true when the grid is ready to start\&. The ready condition is set when the grid device is positioned 
.br
at the beginning of the travel (home position)
.PP
\fBReturns\fP
.RS 4
True if the grid device is in Home position
.RE
.PP

.SS "static bool PCB304::isMagnifierDeviceDetected (void)\fC [inline]\fP, \fC [static]\fP"

.PP
This function returns the presence of the magnifier device 
.PP
\fBReturns\fP
.RS 4
True if the Magnifier device has been detected 
.RE
.PP

.SS "void PCB304::runningLoop (void)\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
This routine shall be overridden by the subclass module in order to inplement the specific module features\&. 
.PP
Reimplemented from \fBCanDeviceProtocol\fP\&.
.SS "static void PCB304::setDisplay (bool on_off)\fC [inline]\fP, \fC [static]\fP"

.SS "static void PCB304::setDisplay (short val, unsigned char decimals, bool blink, unsigned char intensity)\fC [inline]\fP, \fC [static]\fP"

.SS "bool PCB304::setGridOffField (bool wait_completion)\fC [static]\fP"

.SS "bool PCB304::setGridOnField (bool wait_completion)\fC [static]\fP"

.SS "static void PCB304::synchGridWithGenerator (bool status)\fC [inline]\fP, \fC [static]\fP"

.PP
This function activates/deactivates the grid synchronizatio with the generator\&. The Grid device moves the grid in home position ready to start: as soon as the START_GRID signal is detected, the grid device starts moving\&.
.PP
\fBParameters\fP
.RS 4
\fIstatus\fP If status == true, the grid shall activate the generator synchronization
.RE
.PP

.br
 
.SH "Member Data Documentation"
.PP 
.SS "\fBPCB304\fP ^ PCB304::device = gcnew \fBPCB304\fP()\fC [static]\fP"

.SS "bool PCB304::display_blink = false\fC [static]\fP, \fC [private]\fP"

.SS "\fBRegister\fP ^ PCB304::display_data_register = gcnew \fBRegister\fP()\fC [static]\fP, \fC [private]\fP"

.SS "unsigned char PCB304::display_decimals = 0\fC [static]\fP, \fC [private]\fP"

.SS "unsigned char PCB304::display_intensity = 0\fC [static]\fP, \fC [private]\fP"

.SS "bool PCB304::display_on = false\fC [static]\fP, \fC [private]\fP"

.SS "short PCB304::display_val = 0\fC [static]\fP, \fC [private]\fP"

.SS "bool PCB304::error = false\fC [static]\fP, \fC [private]\fP"

.PP
The 2D grid is in error condition\&. 
.SS "\fBRegister\fP ^ PCB304::grid_data_register = gcnew \fBRegister\fP()\fC [static]\fP, \fC [private]\fP"

.SS "bool PCB304::grid_off_field_ready = false\fC [static]\fP, \fC [private]\fP"

.PP
This flag stands for grid correctly positioned out of Field\&. 
.SS "bool PCB304::grid_on_field = false\fC [static]\fP, \fC [private]\fP"

.PP
This is the status of the current grid position\&. 
.SS "bool PCB304::grid_on_field_ready = false\fC [static]\fP, \fC [private]\fP"

.PP
This flag stands for grid correctly positioned in Field\&. 
.SS "bool PCB304::grid_sync_ready = false\fC [static]\fP, \fC [private]\fP"

.PP
This flag stands for grid ready to be activated by the generator\&. 
.SS "bool PCB304::magnifier_device_detected = false\fC [static]\fP, \fC [private]\fP"

.PP
Is set if the Magnifier device has been detected\&. 
.SS "System::String ^ PCB304::magnifier_factor_string = '1\&.0'\fC [static]\fP, \fC [private]\fP"

.PP
This is the current magnification factor detected in string format\&. 
.SS "bool PCB304::synch_grid = false\fC [static]\fP, \fC [private]\fP"

.PP
This flag set the current synch status\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
