.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS/SlideMotor.cpp" 3 "Wed May 29 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS/SlideMotor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'SlideMotor\&.h'\fP
.br
\fC#include 'Notify\&.h'\fP
.br
\fC#include 'pd4_od\&.h'\fP
.br
\fC#include 'VerticalMotor\&.h'\fP
.br
\fC#include 'ArmMotor\&.h'\fP
.br
\fC#include 'TiltMotor\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGEAR_RATIO\fP   ((double) 1 / (double) 29\&.1)"
.br
.ti -1c
.RI "#define \fBMAX_ROTATION_ANGLE\fP   8900"
.br
.ti -1c
.RI "#define \fBMIN_ROTATION_ANGLE\fP   0"
.br
.ti -1c
.RI "#define \fBHOMING_ON_METHOD\fP   19"
.br
.ti -1c
.RI "#define \fBHOMING_OFF_METHOD\fP   20"
.br
.ti -1c
.RI "#define \fBSLIDE_OD_CODE\fP   0x0001"
.br
.RI "The \fBSlideMotor\fP override this function in order to initialize specific motor registers "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GEAR_RATIO   ((double) 1 / (double) 29\&.1)"

.SS "#define HOMING_OFF_METHOD   20"

.SS "#define HOMING_ON_METHOD   19"

.SS "#define MAX_ROTATION_ANGLE   8900"

.SS "#define MIN_ROTATION_ANGLE   0"

.SS "#define SLIDE_OD_CODE   0x0001"

.PP
The \fBSlideMotor\fP override this function in order to initialize specific motor registers 
.PP
\fBReturns\fP
.RS 4
true if the initialization termines successfully
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
