.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/WINDOWS/ValuePopup.cpp" 3 "Wed May 29 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/WINDOWS/ValuePopup.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ValuePopup\&.h'\fP
.br
\fC#include 'gantry_global_status\&.h'\fP
.br
\fC#include 'Log\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFORM_BACKGROUND\fP   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\DIALOG_BACKGROUND\&.PNG')"
.br
.ti -1c
.RI "#define \fBINFO_WINDOW_TMO\fP   15000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FORM_BACKGROUND   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\DIALOG_BACKGROUND\&.PNG')"

.SS "#define INFO_WINDOW_TMO   15000"

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
