.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS/ArmMotor.cpp" 3 "Wed Oct 18 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS/ArmMotor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ArmMotor\&.h'\fP
.br
\fC#include 'verticalMotor\&.h'\fP
.br
\fC#include '\&.\&./gantry_global_status\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBROT_PER_CDEGREE\fP   ((double) 112/ (double) 36000)"
.br
.ti -1c
.RI "#define \fBCOMPRESSION_PLANE_MM\fP   ((double) 100)"
.br
.RI "Distance from the compression plane and the C-ARM rotation axe\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COMPRESSION_PLANE_MM   ((double) 100)"

.PP
Distance from the compression plane and the C-ARM rotation axe\&. 
.SS "#define ROT_PER_CDEGREE   ((double) 112/ (double) 36000)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
