.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/AWS/awsProtocol.cpp" 3 "Fri Dec 15 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/AWS/awsProtocol.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./gantry_global_status\&.h'\fP
.br
\fC#include 'awsProtocol\&.h'\fP
.br
\fC#include 'ArmMotor\&.h'\fP
.br
\fC#include 'VerticalMotor\&.h'\fP
.br
\fC#include 'TiltMotor\&.h'\fP
.br
\fC#include 'BodyMotor\&.h'\fP
.br
\fC#include 'SlideMotor\&.h'\fP
.br
\fC#include 'PCB315\&.h'\fP
.br
\fC#include 'PCB302\&.h'\fP
.br
\fC#include 'PCB303\&.h'\fP
.br
\fC#include 'ExposureModule\&.h'\fP
.br
\fC#include 'Generator\&.h'\fP
.br
\fC#include 'SystemConfig\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
