.TH "awsProtoCommands" 3 "Mon May 13 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
awsProtoCommands \- AWS Protocol Command set
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBawsProtocol::EXEC_TestCommand\fP (void)"
.br
.RI "This command requests for the exposure start "
.ti -1c
.RI "void \fBawsProtocol::EXEC_OpenStudy\fP (void)"
.br
.RI "This command shall be sent by AWS to request to Open the Study\&. "
.ti -1c
.RI "void \fBawsProtocol::EXEC_CloseStudy\fP (void)"
.br
.RI "This command shall be sent by AWS to Close a current study and set the \fBGantry\fP in IDLE operating status\&.  "
.ti -1c
.RI "void \fBawsProtocol::SET_ProjectionList\fP (void)"
.br
.RI "This command shall be sent by AWS to set the gantry selectable projections\&. "
.ti -1c
.RI "void \fBawsProtocol::EXEC_ArmPosition\fP (void)"
.br
.RI "This function activate the ARM to a target position; "
.ti -1c
.RI "void \fBawsProtocol::EXEC_AbortProjection\fP (void)"
.br
.RI "This command shall be sent by AWS to invalidate any selected projection\&.  "
.ti -1c
.RI "void \fBawsProtocol::EXEC_TrxPosition\fP (void)"
.br
.RI "This command shall be sent by AWS to activate the Tilting\&. "
.ti -1c
.RI "void \fBawsProtocol::SET_TomoConfig\fP (void)"
.br
.RI "This command select the current Tomo sequence from the Tomo Configuration file\&. "
.ti -1c
.RI "void \fBawsProtocol::SET_ExposureMode\fP (void)"
.br
.RI "This command select the Exposure Mode for the incoming Exposure sequence "
.ti -1c
.RI "void \fBawsProtocol::SET_ExposureData\fP (void)"
.br
.RI "This command assignes the exposure parameters for the next Exposure pulse "
.ti -1c
.RI "void \fBawsProtocol::SET_EnableXrayPush\fP (void)"
.br
.RI "This command assignes the exposure parameters for the next Exposure pulse  "
.ti -1c
.RI "void \fBawsProtocol::GET_ReadyForExposure\fP (void)"
.br
.RI "This command request for the current status of the ready for exposure "
.ti -1c
.RI "void \fBawsProtocol::EXEC_StartXraySequence\fP (void)"
.br
.RI "This command requests for the exposure start "
.ti -1c
.RI "void \fBawsProtocol::GET_Compressor\fP (void)"
.br
.RI "This command requests the Compressor data: "
.ti -1c
.RI "void \fBawsProtocol::GET_Components\fP (void)"
.br
.RI "This command requests the component identified by the system\&. "
.ti -1c
.RI "void \fBawsProtocol::GET_Trx\fP (void)"
.br
.RI "This command provides the current TRX position: "
.ti -1c
.RI "void \fBawsProtocol::GET_Arm\fP (void)"
.br
.RI "This command provides the current ARM position  "
.ti -1c
.RI "void \fBawsProtocol::GET_TubeTemperature\fP (void)"
.br
.RI "This command returns the Tube cumeulated energy for the Anode and the internal Filament and Stator device\&. "
.ti -1c
.RI "void \fBawsProtocol::SET_Language\fP (void)"
.br
.RI "This command sets the GUI language\&. "
.ti -1c
.RI "void \fBawsProtocol::EXEC_PowerOff\fP (void)"
.br
.ti -1c
.RI "void \fBawsProtocol::AWS_NotRecognizedCommand\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.br
 
.SH "Function Documentation"
.PP 
.SS "void awsProtocol::AWS_NotRecognizedCommand (void)\fC [inline]\fP, \fC [private]\fP"

.SS "void awsProtocol::EXEC_AbortProjection (void)\fC [private]\fP"

.PP
This command shall be sent by AWS to invalidate any selected projection\&.  When the \fBGantry\fP executes this command, the current projection is invalidated:
.IP "\(bu" 2
The exposure cannot be further initiated until a new projection is selected\&.
.PP
.PP
The ARM remains in the current position when the projection is invalidated, but the system display will remove the projection icon from the panel\&.
.PP
Frame format:
.br
<ID % EXEC_AbortProjection >
.PP
PARAMETER   Data Type   Description    -   -   -   
.PP
Possibly returned error codes:
.PP
ERROR CODE   ERROR STRING   DESCRIPTION    \fBreturn_errors::AWS_RET_WRONG_OPERATING_STATUS\fP   'NOT_IN_OPEN_MODE'   The gantry is not in Open Status mode   
.SS "void awsProtocol::EXEC_ArmPosition (void)\fC [private]\fP"

.PP
This function activate the ARM to a target position; The target data in the ArmStatus are updated;
.PP
if the target angle is different of more than 1° then the ArmStatus::target_change_event() is generated and the ARM activation initiates\&.
.PP
This command shall be sent by AWS to activate the C-ARM to a given projection\&.
.PP
In operating mode (Open Study) the AWS controls the ARM angle position using this command\&.
.PP
Frame format:
.br
<ID % EXEC_ArmPosition projection Angle Min Max>
.PP
PARAMETER   Data Type   Description    projection   String   Name of the projection the AWS is selecting    Angle   Integer   Degree of the target angle    Min   Integer   Degree of the minimum acceptable angle    Max   Integer   Degree of the maximum acceptable angle   
.PP
.IP "\(bu" 2
Projection name: it shall be present in the list of the selectable projections (see the 'SET_ProjectionList' command);
.IP "\(bu" 2
Angle: is the target Angle the AWS assign to the projection\&. Is up to the AWS to decide what is the right angle\&.
.IP "\(bu" 2
The Min and the Max value define the acceptable range in the case the operator should manually change the projection angle:
.IP "  \(bu" 4
if the actual ARM angle should be < Min or > Max the gantry will reject the Exposure activation;
.PP

.PP
.PP
NOTE:
.IP "\(bu" 2
the Min shall be < Ange;
.IP "\(bu" 2
the Max shall be > Ange;
.PP
.PP
Possibly returned error codes:
.PP
ERROR CODE   ERROR STRING   DESCRIPTION    \fBreturn_errors::AWS_RET_WRONG_OPERATING_STATUS\fP   'NOT_IN_OPEN_MODE'   the \fBGantry\fP is not in Open Study operating status    \fBreturn_errors::AWS_RET_WRONG_PARAMETERS\fP   'WRONG_NUMBER_OF_PARAMETERS'   the number of parameters is not correct (it should be 4)    \fBreturn_errors::AWS_RET_DEVICE_BUSY\fP   'MOTORS_BUSY'   One of the motors is running    \fBreturn_errors::AWS_RET_DEVICE_BUSY\fP   'ARM_NOT_READY'   The ARM is not ready to execute an activation    \fBreturn_errors::AWS_RET_DATA_NOT_ALLOWED\fP   'WRONG_PROJECTION'   The projection name is not valid or it isn't in the list of selectable projections    \fBreturn_errors::AWS_RET_INVALID_PARAMETER_VALUE\fP   'WRONG_TARGET_DATA'   One of the angle parameter is not correct or out of range   
.PP
The Command always returns a <ID % EXECUTING%> frame in case of success, because the ARM requires some time to be positioned, even if the ARM should be already in the target position\&.
.SS "void awsProtocol::EXEC_CloseStudy (void)\fC [private]\fP"

.PP
This command shall be sent by AWS to Close a current study and set the \fBGantry\fP in IDLE operating status\&.  Frame format:
.br
<ID % EXEC_CloseStudy >
.PP
PARAMETER   Data Type   Description    -   -   -   
.PP
Possibly returned error codes:
.PP
ERROR CODE   ERROR STRING   DESCRIPTION    \fBreturn_errors::AWS_RET_WRONG_OPERATING_STATUS\fP   'NOT_IN_OPEN_MODE'   The gantry is not in Open Status mode   
.SS "void awsProtocol::EXEC_OpenStudy (void)\fC [private]\fP"

.PP
This command shall be sent by AWS to request to Open the Study\&. The Open Study is necessary to enter the Operating Status\&.
.PP
Frame format:
.br
<ID % EXEC_OpenStudy 'patient_name'>
.PP
PARAMETER   Data Type   Description    patient_name   String   Study's patient name   
.PP
Possibly returned error codes:
.PP
ERROR CODE   ERROR STRING   DESCRIPTION    \fBreturn_errors::AWS_RET_SYSTEM_ERRORS\fP   'SYSTEM_ERRORS'   system error condition are presents    \fBreturn_errors::AWS_RET_WRONG_PARAMETERS\fP   'WRONG_NUMBER_OF_PARAMETERS'   wrong number of parameters (it should be 1)    \fBreturn_errors::AWS_RET_WRONG_OPERATING_STATUS\fP   'NOT_IN_IDLE_MODE'   the \fBGantry\fP is not in IDLE status   
.SS "void awsProtocol::EXEC_PowerOff (void)\fC [inline]\fP, \fC [private]\fP"

.SS "void awsProtocol::EXEC_StartXraySequence (void)\fC [private]\fP"

.PP
This command requests for the exposure start 
.SS "void awsProtocol::EXEC_TestCommand (void)\fC [private]\fP"

.PP
This command requests for the exposure start 
.SS "void awsProtocol::EXEC_TrxPosition (void)\fC [private]\fP"

.PP
This command shall be sent by AWS to activate the Tilting\&. Frame format:
.br
<ID % EXEC_TrxPosition trx_target>
.PP
PARAMETER   Data Type   Description    trx_target   String   the TRX target position\&. See table below   
.PP
TRX TARGET VALUE   DESCRIPTION    'SCOUT'   Scout Position    'BP_R'   \fBBiopsy\fP Right Position    'BP_L'   \fBBiopsy\fP left Position    'TOMO_H'   Tomo Home Position    'TOMO_E'   Tomo Final Position   
.PP
Possibly returned error codes:
.PP
ERROR CODE   ERROR STRING   DESCRIPTION    \fBreturn_errors::AWS_RET_WRONG_OPERATING_STATUS\fP   'NOT_IN_OPEN_MODE'   the \fBGantry\fP is not in Open Study operating status    \fBreturn_errors::AWS_RET_WRONG_PARAMETERS\fP   'WRONG_NUMBER_OF_PARAMETERS'   the number of parameters is not correct (it should be 1)    \fBreturn_errors::AWS_RET_DEVICE_BUSY\fP   'MOTORS_BUSY'   One of the motors is running    \fBreturn_errors::AWS_RET_DEVICE_BUSY\fP   'TRX_NOT_READY'   The TRX is not ready to execute an activation    \fBreturn_errors::AWS_RET_INVALID_PARAMETER_VALUE\fP   'INVALID_TARGET'   One of the angle parameter is not correct or out of range    \fBreturn_errors::AWS_RET_DEVICE_ERROR\fP   'DEVICE_ERROR'   The Tilt Device cannot activate the command for an internal reason   
.PP
\fBGantry\fP always returns <ID % EXECUTING%> frame: the TRX start executing;
.SS "void awsProtocol::GET_Arm (void)\fC [private]\fP"

.PP
This command provides the current ARM position  
.SS "void awsProtocol::GET_Components (void)\fC [private]\fP"

.PP
This command requests the component identified by the system\&. 
.IP "\(bu" 2
Potter-Type, Mag Factor, ComprPaddle, ProtectionType, CollimationTool 
.PP

.SS "void awsProtocol::GET_Compressor (void)\fC [private]\fP"

.PP
This command requests the Compressor data: 
.IP "\(bu" 2
Compressor Thickness;
.IP "\(bu" 2
Compressore Force;
.PP

.SS "void awsProtocol::GET_ReadyForExposure (void)\fC [private]\fP"

.PP
This command request for the current status of the ready for exposure 
.SS "void awsProtocol::GET_Trx (void)\fC [private]\fP"

.PP
This command provides the current TRX position: 
.IP "\(bu" 2
The Symbolic position;
.IP "\(bu" 2
The actual angle position;
.PP

.SS "void awsProtocol::GET_TubeTemperature (void)\fC [private]\fP"

.PP
This command returns the Tube cumeulated energy for the Anode and the internal Filament and Stator device\&. 
.SS "void awsProtocol::SET_EnableXrayPush (void)\fC [private]\fP"

.PP
This command assignes the exposure parameters for the next Exposure pulse  
.SS "void awsProtocol::SET_ExposureData (void)\fC [private]\fP"

.PP
This command assignes the exposure parameters for the next Exposure pulse 
.SS "void awsProtocol::SET_ExposureMode (void)\fC [private]\fP"

.PP
This command select the Exposure Mode for the incoming Exposure sequence 
.SS "void awsProtocol::SET_Language (void)\fC [private]\fP"

.PP
This command sets the GUI language\&. 
.SS "void awsProtocol::SET_ProjectionList (void)\fC [private]\fP"

.PP
This command shall be sent by AWS to set the gantry selectable projections\&. The AWS provides a set of projection that the operator can select
.br
from the local displays\&.
.PP
Frame format:
.br
<ID % SET_ProjectionList proj1, proj2, \&.\&. , proj-n>
.PP
PARAMETER   Data Type   Description    proj1\&.\&.proj-n   Projection name   List of the selectable projections   
.PP
Possibly returned error codes:
.PP
ERROR CODE   ERROR STRING   DESCRIPTION    \fBreturn_errors::AWS_RET_WRONG_OPERATING_STATUS\fP   'NOT_IN_OPEN_MODE'   the \fBGantry\fP is not in Open Study operating status    \fBreturn_errors::AWS_RET_INVALID_PARAMETER_VALUE\fP   'INVALID_PROJECTION_IN_THE_LIST'   a projection name in the list is not valid   
.SS "void awsProtocol::SET_TomoConfig (void)\fC [private]\fP"

.PP
This command select the current Tomo sequence from the Tomo Configuration file\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
