.TH "BodyMotor_Module" 3 "Thu May 2 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BodyMotor_Module \- Body Module controller
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBodyMotor\fP"
.br
.RI "This is the Body Module class implementation"
.in -1c
.SH "Detailed Description"
.PP 


This module implements the Body rotation requirements\&.
.SH "Motor Mechanical Assembly setup"
.PP
.IP "\(bu" 2
The Motor gear ratio is 80-1: 80 motor turns equal to 360 degree body rotation;
.IP "\(bu" 2
When the motor rotates clockwise, the Body rotates counter_clockwise (viewed from the Body Top);
.IP "\(bu" 2
The Zero setting photocell:
.IP "  \(bu" 4
when it is ON (on light) the body has to rotate clockwise (the motor rotate counter_clockwise) to find the center;
.IP "  \(bu" 4
when it is OFF (obscured) the body has to rotate counter_clockwise (the motor rotate clockwise) to find the center;
.PP

.IP "\(bu" 2
Limit switch photocell OFF (obscured):
.IP "  \(bu" 4
with Zero setting ON: the limit is the counter-clockwise;
.IP "  \(bu" 4
with Zero setting OFF: the limit is the clockwise;
.PP

.PP
.SH "Motor GPIO assignment"
.PP
.SS "Analog Input"
The Analog input is used to detect the actual position of the shaft\&.
.PP
The position is detected using a 5 turns potentiometer connected to the shaft with a x3 multiply factor:
.PP
180° -> 1\&.5 potentiometer turns\&.
.PP
The calculated resolution is 0\&.4882 °/unit
.SS "Digital Inputs"
.IP "\(bu" 2
DIGITAL INPUT 4: Brake activation status;
.PP
.PP
The Input4 is a Positive logic assigned to the current brake status:
.IP "\(bu" 2
ON: the brake is powered;
.IP "\(bu" 2
OFF: the brake is not powered;
.PP
.PP
NOTE: the Brake device is a normally closed brake, so when it should be powered, it releases the braking force!
.SS "Digital Outputs"
.IP "\(bu" 2
DIGITAL OUTPUT 1 and 2: brake activation outputs
.PP
.PP
The Output are tw open collector output that shall be set as Normally closed (OFF = 0V output)\&.
.PP
In order to power the Brake device both Outpuyt shall be set ON\&.
.PP
The use of the Output should be:
.IP "\(bu" 2
OUTPUT2 shall be set normally ON: ift should be set OFF only in case of brake malfunction;
.IP "\(bu" 2
OUTPUT1 shall be set ON/OFF to control the actual brake status;
.PP
NOTE: The OUPUT2 should be kept ON because this status should guarantee that one of the power Mosfet controlling the Brake remains working in case, for any reason, the other Mosfet should be broken\&.
.PP
.SH "Position unit definition"
.PP
.IP "\(bu" 2
The module provides the position readout in the range of +/- 180 degrees;
.IP "\(bu" 2
The allowed activation is in the range of +/- 90° with a precision of 0\&.1 degree;
.IP "\(bu" 2
The positive angle is the counter-clockwise direction (from the TOP View);
.PP
.SH "Brake Diagnostic Test"
.PP
The Brake activation is tested at the beginning during the motor initialization, and during the Motor IDLE status\&.
.SS "Brake Test at the Initialization"
During the Motor Initialization, both the OUTPUT1 and OUTPUT2 shall be set to OFF,
.br
 and the Input4 should be OFF:
.IP "\(bu" 2
In case Input4 should be ON, a non resettable fault condition is generated\&.
.PP
.SS "Brake Test in IDLE"
During the IDLE mode, the OUTPUT 2 is kept ONand the OUTPUT1 is set OFF:
.IP "\(bu" 2
In case the Input4 should be detected ON, a non resettable fault condition is generated\&.
.PP
.SS "Brake Fault Condition"
In case a Brake device should be detected in Fault, the OUTPUT1 and OUTPUT2 will both be set OFF and a relevant non resettable alarm will be generated\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
