.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS/BodyMotor.cpp" 3 "Wed Nov 29 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS/BodyMotor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CalibrationConfig\&.h'\fP
.br
\fC#include 'Errors\&.h'\fP
.br
\fC#include 'BodyMotor\&.h'\fP
.br
\fC#include 'pd4_od\&.h'\fP
.br
\fC#include <thread>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBROT_PER_DEGREE\fP   ((double) 80 / (double) 3600)"
.br
.RI "Defines the internal unit in 0\&.1 degrees for unit\&. "
.ti -1c
.RI "#define \fBBRAKE_INPUT_MASK\fP(x)   (x & 0x00080000)"
.br
.RI "Not in the Special region [00II][0000]\&. "
.ti -1c
.RI "#define \fBOUPUT1_OUT_MASK\fP   0x00010000"
.br
.RI "Not in the Special region [00II][0000]\&. "
.ti -1c
.RI "#define \fBOUPUT2_OUT_MASK\fP   0x00020000"
.br
.RI "Not in the Special region [00II][0000]\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BRAKE_INPUT_MASK(x)   (x & 0x00080000)"

.PP
Not in the Special region [00II][0000]\&. 
.SS "#define OUPUT1_OUT_MASK   0x00010000"

.PP
Not in the Special region [00II][0000]\&. 
.SS "#define OUPUT2_OUT_MASK   0x00020000"

.PP
Not in the Special region [00II][0000]\&. 
.SS "#define ROT_PER_DEGREE   ((double) 80 / (double) 3600)"

.PP
Defines the internal unit in 0\&.1 degrees for unit\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
