.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS Directory Reference" 3 "Wed Oct 18 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArmMotor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBArmMotor\&.h\fP"
.br
.ti -1c
.RI "file \fBCanOpenMotor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCanOpenMotor\&.h\fP"
.br
.ti -1c
.RI "file \fBpd4_od\&.h\fP"
.br
.ti -1c
.RI "file \fBTiltMotor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTiltMotor\&.h\fP"
.br
.ti -1c
.RI "file \fBVerticalMotor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBVerticalMotor\&.h\fP"
.br
.in -1c
