.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/WINDOWS Directory Reference" 3 "Mon May 13 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/WINDOWS Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConfirmationWindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBConfirmationWindow\&.h\fP"
.br
.ti -1c
.RI "file \fBErrorForm\&.cpp\fP"
.br
.ti -1c
.RI "file \fBErrorForm\&.h\fP"
.br
.ti -1c
.RI "file \fBIconWindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIconWindow\&.h\fP"
.br
.ti -1c
.RI "file \fBIdleForm\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIdleForm\&.h\fP"
.br
.ti -1c
.RI "file \fBinfoPopup\&.cpp\fP"
.br
.ti -1c
.RI "file \fBinfoPopup\&.h\fP"
.br
.ti -1c
.RI "file \fBKeyPaddle\&.cpp\fP"
.br
.ti -1c
.RI "file \fBKeyPaddle\&.h\fP"
.br
.ti -1c
.RI "file \fBMainForm\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMainForm\&.h\fP"
.br
.ti -1c
.RI "file \fBOperatingForm\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOperatingForm\&.h\fP"
.br
.ti -1c
.RI "file \fBProjections\&.cpp\fP"
.br
.ti -1c
.RI "file \fBProjections\&.h\fP"
.br
.ti -1c
.RI "file \fBValuePopup\&.cpp\fP"
.br
.ti -1c
.RI "file \fBValuePopup\&.h\fP"
.br
.in -1c
