.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS Directory Reference" 3 "Mon May 13 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCanOpenDriver\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArmMotor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBArmMotor\&.h\fP"
.br
.ti -1c
.RI "file \fBBodyMotor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBodyMotor\&.h\fP"
.br
.ti -1c
.RI "file \fBSlideMotor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSlideMotor\&.h\fP"
.br
.ti -1c
.RI "file \fBTiltMotor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTiltMotor\&.h\fP"
.br
.ti -1c
.RI "file \fBVerticalMotor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBVerticalMotor\&.h\fP"
.br
.in -1c
