.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/CONFIGURATION/CalibrationConfig.h" 3 "Mon May 13 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/CONFIGURATION/CalibrationConfig.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ConfigFile\&.h'\fP
.br
\fC#include 'PCB326\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMotorConfig\fP"
.br
.ti -1c
.RI "class \fBFilterConfig\fP"
.br
.ti -1c
.RI "class \fBCompressorConfig\fP"
.br
.ti -1c
.RI "class \fBCollimatorConfig\fP"
.br
.ti -1c
.RI "class \fBPaddleConfig\fP"
.br
.ti -1c
.RI "class \fBTomoConfig\fP"
.br
.ti -1c
.RI "class \fBDetectorConfig\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
