.TH "CanDeviceProtocol::CanDeviceRegister" 3 "Wed Nov 29 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CanDeviceProtocol::CanDeviceRegister
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CanDeviceProtocol\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCanDeviceRegister\fP (void)"
.br
.ti -1c
.RI "bool \fBdecode\fP (unsigned char *data, bool bootl)"
.br
.ti -1c
.RI "void \fBformat\fP (unsigned char *data)"
.br
.ti -1c
.RI "void \fBset\fP (unsigned char d0, unsigned char d1, unsigned char d2, unsigned char d3, unsigned char d4, unsigned char d5, unsigned char d6, unsigned char d7, bool bootl)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBb0\fP"
.br
.ti -1c
.RI "unsigned char \fBb1\fP"
.br
.ti -1c
.RI "unsigned char \fBb2\fP"
.br
.ti -1c
.RI "unsigned char \fBb3\fP"
.br
.ti -1c
.RI "unsigned char \fBb4\fP"
.br
.ti -1c
.RI "unsigned char \fBb5\fP"
.br
.ti -1c
.RI "unsigned char \fBb6\fP"
.br
.ti -1c
.RI "unsigned char \fBb7\fP"
.br
.ti -1c
.RI "unsigned char \fBcrc\fP"
.br
.ti -1c
.RI "bool \fBbootloader\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CanDeviceProtocol::CanDeviceRegister::CanDeviceRegister (void)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool CanDeviceProtocol::CanDeviceRegister::decode (unsigned char * data, bool bootl)\fC [inline]\fP"

.SS "void CanDeviceProtocol::CanDeviceRegister::format (unsigned char * data)\fC [inline]\fP"

.SS "void CanDeviceProtocol::CanDeviceRegister::set (unsigned char d0, unsigned char d1, unsigned char d2, unsigned char d3, unsigned char d4, unsigned char d5, unsigned char d6, unsigned char d7, bool bootl)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned char CanDeviceProtocol::CanDeviceRegister::b0"

.SS "unsigned char CanDeviceProtocol::CanDeviceRegister::b1"

.SS "unsigned char CanDeviceProtocol::CanDeviceRegister::b2"

.SS "unsigned char CanDeviceProtocol::CanDeviceRegister::b3"

.SS "unsigned char CanDeviceProtocol::CanDeviceRegister::b4"

.SS "unsigned char CanDeviceProtocol::CanDeviceRegister::b5"

.SS "unsigned char CanDeviceProtocol::CanDeviceRegister::b6"

.SS "unsigned char CanDeviceProtocol::CanDeviceRegister::b7"

.SS "bool CanDeviceProtocol::CanDeviceRegister::bootloader"

.SS "unsigned char CanDeviceProtocol::CanDeviceRegister::crc"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
