.TH "CanDeviceProtocol::Register" 3 "Thu May 2 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CanDeviceProtocol::Register
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CanDeviceProtocol\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegister\fP (unsigned char pd0, unsigned char pd1, unsigned char pd2, unsigned char pd3)"
.br
.ti -1c
.RI "\fBRegister\fP (void)"
.br
.ti -1c
.RI "void \fBD0\fP (bool stat, unsigned char mask)"
.br
.ti -1c
.RI "void \fBD1\fP (bool stat, unsigned char mask)"
.br
.ti -1c
.RI "void \fBD2\fP (bool stat, unsigned char mask)"
.br
.ti -1c
.RI "void \fBD3\fP (bool stat, unsigned char mask)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBd0\fP"
.br
.ti -1c
.RI "unsigned char \fBd1\fP"
.br
.ti -1c
.RI "unsigned char \fBd2\fP"
.br
.ti -1c
.RI "unsigned char \fBd3\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CanDeviceProtocol::Register::Register (unsigned char pd0, unsigned char pd1, unsigned char pd2, unsigned char pd3)\fC [inline]\fP"

.SS "CanDeviceProtocol::Register::Register (void)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void CanDeviceProtocol::Register::D0 (bool stat, unsigned char mask)\fC [inline]\fP"

.SS "void CanDeviceProtocol::Register::D1 (bool stat, unsigned char mask)\fC [inline]\fP"

.SS "void CanDeviceProtocol::Register::D2 (bool stat, unsigned char mask)\fC [inline]\fP"

.SS "void CanDeviceProtocol::Register::D3 (bool stat, unsigned char mask)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned char CanDeviceProtocol::Register::d0"

.SS "unsigned char CanDeviceProtocol::Register::d1"

.SS "unsigned char CanDeviceProtocol::Register::d2"

.SS "unsigned char CanDeviceProtocol::Register::d3"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
