.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/DEVICES/CanDeviceProtocol.h" 3 "Wed Nov 29 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/DEVICES/CanDeviceProtocol.h
.SH SYNOPSIS
.br
.PP
\fC#include <Windows\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCanDeviceProtocol\fP"
.br
.ti -1c
.RI "class \fBCanDeviceProtocol::Register\fP"
.br
.ti -1c
.RI "class \fBCanDeviceProtocol::CanDeviceRegister\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGET_BOOTLOADER_INFO\fP   (System::Byte) 0x1, (System::Byte) 0,(System::Byte) 0, (System::Byte) 0,(System::Byte) 0,(System::Byte) 0, (System::Byte) 0,(System::Byte) 0,true"
.br
.ti -1c
.RI "#define \fBGET_COMMAND_REGISTER\fP   (System::Byte) 0, (System::Byte) 3,(System::Byte) 0, (System::Byte) 0,(System::Byte) 0,(System::Byte) 0, (System::Byte) 0,(System::Byte) 0,false"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GET_BOOTLOADER_INFO   (System::Byte) 0x1, (System::Byte) 0,(System::Byte) 0, (System::Byte) 0,(System::Byte) 0,(System::Byte) 0, (System::Byte) 0,(System::Byte) 0,true"

.SS "#define GET_COMMAND_REGISTER   (System::Byte) 0, (System::Byte) 3,(System::Byte) 0, (System::Byte) 0,(System::Byte) 0,(System::Byte) 0, (System::Byte) 0,(System::Byte) 0,false"

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
