.TH "CanDeviceProtocol::Register" 3 "Wed Nov 29 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CanDeviceProtocol::Register
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CanDeviceProtocol\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegister\fP (unsigned char pd0, unsigned char pd1, unsigned char pd2, unsigned char pd3)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBd0\fP"
.br
.ti -1c
.RI "unsigned char \fBd1\fP"
.br
.ti -1c
.RI "unsigned char \fBd2\fP"
.br
.ti -1c
.RI "unsigned char \fBd3\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CanDeviceProtocol::Register::Register (unsigned char pd0, unsigned char pd1, unsigned char pd2, unsigned char pd3)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned char CanDeviceProtocol::Register::d0"

.SS "unsigned char CanDeviceProtocol::Register::d1"

.SS "unsigned char CanDeviceProtocol::Register::d2"

.SS "unsigned char CanDeviceProtocol::Register::d3"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
