.TH "CanDevice_Module" 3 "Thu May 2 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CanDevice_Module \- Device board modules based on CAN bus protocol
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPCB301 Module: power service board module control\fP"
.br
.RI ""
.ti -1c
.RI "\fBPCB302 Module: Compressor device module controller\fP"
.br
.RI ""
.ti -1c
.RI "\fBPCB303 Module: format collimation\fP"
.br
.RI "This module implements the functions of the Collimator device "
.ti -1c
.RI "\fBPCB304 Module: Grid device module controller\fP"
.br
.RI "<>  "
.ti -1c
.RI "\fBPCB315 Module: filter selection and tube temperature control\fP"
.br
.RI "This module implements the functions of the Filter device "
.ti -1c
.RI "\fBPCB326 Module: Obstacle device module controller\fP"
.br
.RI ""
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCanDeviceProtocol\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 


This module implements the genera device communication protocol based on the CAN bus
.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
