.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS/CanOpenDriver/CanOpenHoming.cpp" 3 "Thu May 2 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS/CanOpenDriver/CanOpenHoming.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CanDriver\&.h'\fP
.br
\fC#include 'Notify\&.h'\fP
.br
\fC#include 'CanOpenMotor\&.h'\fP
.br
\fC#include 'gantry_global_status\&.h'\fP
.br
\fC#include 'pd4_od\&.h'\fP
.br
\fC#include <thread>\fP
.br
\fC#include 'Log\&.h'\fP
.br
\fC#include 'CalibrationConfig\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBZERO_INPUT_MASK\fP(x)   (x & 0x00040000)"
.br
.RI "Not in the Special region [00II][0000]\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ZERO_INPUT_MASK(x)   (x & 0x00040000)"

.PP
Not in the Special region [00II][0000]\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
