.TH "CanOpenModule" 3 "Mon May 13 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CanOpenModule \- CanOPEN based motor devices
.PP
 \- This is the based class module implementing the control of motor devices based on the CANOpen protocol\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBC\-ARM Module controller\fP"
.br
.RI ""
.ti -1c
.RI "\fBBody Module controller\fP"
.br
.RI ""
.ti -1c
.RI "\fBTilt Motor Module controller\fP"
.br
.RI "This module implements the Tilt activation requirements\&. "
.ti -1c
.RI "\fBVertical Module controller\fP"
.br
.RI "This module implements the Vertical activation requirements\&. "
.ti -1c
.RI "\fBMotor Driver base class module\fP"
.br
.RI "This is the Class implementing the CanOPEN Motor Device control protocol\&. "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCANOPEN::ODRegister\fP"
.br
.RI "This is the class implementating the CanOPEN SDO object register\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCANOPEN::MotorDeviceAddresses\fP { \fBCANOPEN::MotorDeviceAddresses::TILT_ID\fP = 0x3, \fBCANOPEN::MotorDeviceAddresses::ARM_ID\fP = 0x4, \fBCANOPEN::MotorDeviceAddresses::SLIDE_ID\fP = 0x5, \fBCANOPEN::MotorDeviceAddresses::BODY_ID\fP = 0x6, \fBCANOPEN::MotorDeviceAddresses::VERTICAL_ID\fP = 0x7 }"
.br
.RI "This is the enumeration of the Application Motor device addresses "
.in -1c
.SH "Detailed Description"
.PP 
This is the based class module implementing the control of motor devices based on the CANOpen protocol\&. 


.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBCANOPEN::MotorDeviceAddresses\fP\fC [strong]\fP"

.PP
This is the enumeration of the Application Motor device addresses 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITILT_ID \fP\fP
Address of the Tilt Motor controller\&. 
.TP
\fB\fIARM_ID \fP\fP
Address of the C-ARM Motor controller\&. 
.TP
\fB\fISLIDE_ID \fP\fP
Address of the SLIDE Motor controller\&. 
.TP
\fB\fIBODY_ID \fP\fP
Address of the BODY Motor controller\&. 
.TP
\fB\fIVERTICAL_ID \fP\fP
Address of the Vertical Motor controller\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
