.TH "CANOPEN" 3 "Wed Nov 29 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CANOPEN
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCanOpenMotor\fP"
.br
.RI "This is the Class implementing the CanOPEN Motor Device control protocol\&. "
.ti -1c
.RI "class \fBODRegister\fP"
.br
.RI "This is the class implementating the CanOPEN SDO object register\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBMotorDeviceAddresses\fP { \fBMotorDeviceAddresses::TILT_ID\fP = 0x3, \fBMotorDeviceAddresses::ARM_ID\fP = 0x4, \fBMotorDeviceAddresses::SLIDE_ID\fP = 0x5, \fBMotorDeviceAddresses::BODY_ID\fP = 0x6, \fBMotorDeviceAddresses::VERTICAL_ID\fP = 0x7 }"
.br
.RI "This is the enumeration of the Application Motor device addresses "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
