.TH "ConfigFile::paramItemT" 3 "Wed Nov 29 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigFile::paramItemT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ConfigFile\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBparamItemT\fP (const System::String^ tg, const System::String^ cmt, cli::array< const System::String^>^ def)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const System::String ^ \fBtag\fP"
.br
.RI "Tag name of the parameter\&. "
.ti -1c
.RI "cli::array< const System::String^> ^ \fBdefaults\fP"
.br
.RI "Default Value list of a parameter\&. "
.ti -1c
.RI "const System::String ^ \fBcomment\fP"
.br
.RI "comment "
.ti -1c
.RI "cli::array< System::String^> ^ \fBvalues\fP"
.br
.RI "Value list of a parameter\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConfigFile::paramItemT::paramItemT (const System::String^ tg, const System::String^ cmt, cli::array< const System::String^>^ def)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const System::String ^ ConfigFile::paramItemT::comment"

.PP
comment 
.SS "cli::array<const System::String^> ^ ConfigFile::paramItemT::defaults"

.PP
Default Value list of a parameter\&. 
.SS "const System::String ^ ConfigFile::paramItemT::tag"

.PP
Tag name of the parameter\&. 
.SS "cli::array<System::String^> ^ ConfigFile::paramItemT::values"

.PP
Value list of a parameter\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
