.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/WINDOWS/ConfirmationWindow.cpp" 3 "Thu May 2 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/WINDOWS/ConfirmationWindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ConfirmationWindow\&.h'\fP
.br
\fC#include '\&.\&./gantry_global_status\&.h'\fP
.br
\fC#include 'Log\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBERR_ICON_IMAGE\fP   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\error_160x145\&.PNG')"
.br
.ti -1c
.RI "#define \fBINFO_ICON_IMAGE\fP   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\info_64x64\&.PNG')"
.br
.ti -1c
.RI "#define \fBWRN_ICON_IMAGE\fP   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\info_64x64\&.PNG')"
.br
.ti -1c
.RI "#define \fBCANC_IMAGE\fP   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\CANC_ICON\&.PNG')"
.br
.ti -1c
.RI "#define \fBOK_IMAGE\fP   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\OK_ICON\&.PNG')"
.br
.ti -1c
.RI "#define \fBFORM_BACKGROUND\fP   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\DIALOG_BACKGROUND\&.PNG')"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CANC_IMAGE   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\CANC_ICON\&.PNG')"

.SS "#define ERR_ICON_IMAGE   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\error_160x145\&.PNG')"

.SS "#define FORM_BACKGROUND   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\DIALOG_BACKGROUND\&.PNG')"

.SS "#define INFO_ICON_IMAGE   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\info_64x64\&.PNG')"

.SS "#define OK_IMAGE   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\OK_ICON\&.PNG')"

.SS "#define WRN_ICON_IMAGE   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\info_64x64\&.PNG')"

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
