.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/CppCLR_WinFormsProject.cpp" 3 "Wed Oct 18 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/CppCLR_WinFormsProject.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CanOpenMotor\&.h'\fP
.br
\fC#include 'Translate\&.h'\fP
.br
\fC#include 'Generator\&.h'\fP
.br
\fC#include 'IdleForm\&.h'\fP
.br
\fC#include 'MainForm\&.h'\fP
.br
\fC#include 'OperatingForm\&.h'\fP
.br
\fC#include '\&./gantry_global_status\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
