.TH "debugModule" 3 "Mon May 13 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
debugModule \- Public Debug Methods
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCanDeviceProtocol::CanDeviceCommunicationMonitor\fP"
.br
.RI "This class provides an interface to monitor the communication performance with the device\&. "
.in -1c
.SH "Detailed Description"
.PP 


This section provides debug feature to monitor the communication with the remote device and in general internal module performances\&.
.PP
The available tools are:
.IP "\(bu" 2
CanDeviceCommunicationMonitor: this is a dedicated class that makes statistics on the data exchanges with the remote device to monitor the quality of the communication\&. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
