.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/WINDOWS/ErrorForm.cpp" 3 "Thu May 2 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/WINDOWS/ErrorForm.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ErrorForm\&.h'\fP
.br
\fC#include 'Notify\&.h'\fP
.br
\fC#include 'gantry_global_status\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFORM_IMAGE\fP   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Windows\\\\ErrorFormBackground\&.PNG')"
.br
.ti -1c
.RI "#define \fBERROR_IMAGE\fP   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\error\&.PNG')"
.br
.ti -1c
.RI "#define \fBWARNING_IMAGE\fP   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\warning\&.PNG')"
.br
.ti -1c
.RI "#define \fBINFO_IMAGE\fP   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\info\&.PNG')"
.br
.ti -1c
.RI "#define \fBERROR_WINDOW_TMO\fP   15000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ERROR_IMAGE   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\error\&.PNG')"

.SS "#define ERROR_WINDOW_TMO   15000"

.SS "#define FORM_IMAGE   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Windows\\\\ErrorFormBackground\&.PNG')"

.SS "#define INFO_IMAGE   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\info\&.PNG')"

.SS "#define WARNING_IMAGE   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'Icons\\\\warning\&.PNG')"

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
