.TH "Exposure_Module" 3 "Mon May 13 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exposure_Module \- Exposure Module
.PP
 \- This Module implements the Application exposure sequence workflows\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExposures\fP"
.br
.RI "This Class implements the Exposure data structures and the exposure worflows\&.  "
.ti -1c
.RI "class \fBGenerator\fP"
.br
.RI "This Module class implements the communication and control of the the SHFD Device\&. "
.ti -1c
.RI "class \fBTcpClientCLI\fP"
.br
.RI "This Class implements the Tcp/Ip Client connection with the SmartHub server\&. "
.in -1c
.SH "Detailed Description"
.PP 
This Module implements the Application exposure sequence workflows\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
