.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/GENERATOR/ExposureModule.cpp" 3 "Thu May 2 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/GENERATOR/ExposureModule.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'R2CP_Eth\&.h'\fP
.br
\fC#include 'CaDataDicGen\&.h'\fP
.br
\fC#include 'SystemConfig\&.h'\fP
.br
\fC#include 'Generator\&.h'\fP
.br
\fC#include 'gantry_global_status\&.h'\fP
.br
\fC#include 'ExposureModule\&.h'\fP
.br
\fC#include 'Notify\&.h'\fP
.br
\fC#include 'awsProtocol\&.h'\fP
.br
\fC#include 'ArmMotor\&.h'\fP
.br
\fC#include 'PCB301\&.h'\fP
.br
\fC#include 'PCB302\&.h'\fP
.br
\fC#include 'PCB304\&.h'\fP
.br
\fC#include <thread>\fP
.br
\fC#include 'Log\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
