.TH "ExposureModule::tomo_data" 3 "Thu May 2 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExposureModule::tomo_data
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExposureModule\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtomo_data\fP (void)"
.br
.ti -1c
.RI "void \fBinvalidate\fP (void)"
.br
.ti -1c
.RI "bool \fBset\fP (System::String^ cfg)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "System::String ^ \fBconfigName\fP"
.br
.RI "Name of the selected configuration;\&. "
.ti -1c
.RI "bool \fBvalid\fP"
.br
.RI "A valid selection is present\&. "
.ti -1c
.RI "int \fBtomo_home\fP"
.br
.ti -1c
.RI "int \fBtomo_end\fP"
.br
.ti -1c
.RI "int \fBtomo_skip\fP"
.br
.ti -1c
.RI "int \fBtomo_samples\fP"
.br
.ti -1c
.RI "int \fBtomo_speed\fP"
.br
.ti -1c
.RI "int \fBtomo_acc\fP"
.br
.ti -1c
.RI "int \fBtomo_dec\fP"
.br
.ti -1c
.RI "int \fBtomo_fps\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExposureModule::tomo_data::tomo_data (void)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ExposureModule::tomo_data::invalidate (void)\fC [inline]\fP"

.SS "bool ExposureModule::tomo_data::set (System::String^ cfg)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "System::String ^ ExposureModule::tomo_data::configName"

.PP
Name of the selected configuration;\&. 
.SS "int ExposureModule::tomo_data::tomo_acc"

.SS "int ExposureModule::tomo_data::tomo_dec"

.SS "int ExposureModule::tomo_data::tomo_end"

.SS "int ExposureModule::tomo_data::tomo_fps"

.SS "int ExposureModule::tomo_data::tomo_home"

.SS "int ExposureModule::tomo_data::tomo_samples"

.SS "int ExposureModule::tomo_data::tomo_skip"

.SS "int ExposureModule::tomo_data::tomo_speed"

.SS "bool ExposureModule::tomo_data::valid"

.PP
A valid selection is present\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
