.TH "GantryStatusRegisters::tomoConfig" 3MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatusRegisters::tomoConfig \- This class implements the Tomo configuration selection options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBoptions_conf\fP { \fBTOMO_1F\fP, \fBTOMO_2F\fP, \fBTOMO_3F\fP, \fBTOMO_4F\fP, \fBTOMO_5F\fP, \fBLEN\fP, \fBUNDEF\fP = LEN }"
.br
.RI "This is the enumeration option code for file configuration\&. "
.ti -1c
.RI "enum class \fBoptions_seq\fP { \fBNARROW\fP, \fBINTERMEDIATE\fP, \fBWIDE\fP, \fBSUPERWIDE\fP, \fBLEN\fP, \fBUNDEF\fP = LEN }"
.br
.RI "This is the enumeration option code for the particolar sequence in the configuration file 
.br
 "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBdelegate_selection_change\fP (void)"
.br
.RI "This is the delegate of the status_change_event();\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBselect\fP (String^ conftag, String^ seqtag)"
.br
.RI "This function selects a Tomo configuration sequence based on the confid and seqid identifiers\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const array< String^> ^ \fBtags_conf\fP = gcnew array<String^> { 'TOMO_1F', 'TOMO_2F', 'TOMO_3F', 'TOMO_4F', 'TOMO_5F', 'UNDEF' }"
.br
.RI "This is the config id option-tags static array\&. "
.ti -1c
.RI "static const array< String^> ^ \fBtags_seq\fP = gcnew array<String^> { 'N', 'I', 'W', 'SW', 'UNDEF' }"
.br
.RI "This is the sequence option-tags static array\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static \fBdelegate_selection_change\fP^ \fBselection_change_event\fP"
.br
.RI "This event is generated whenver the status of the register is changed\&. "
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBoptions_conf\fP \fBconfid\fP = \fBoptions_conf::UNDEF\fP"
.br
.RI "This is the register conf_id\&. "
.ti -1c
.RI "static \fBoptions_seq\fP \fBseqid\fP = \fBoptions_seq::UNDEF\fP"
.br
.RI "This is the register sequence_id\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class implements the Tomo configuration selection options\&. 

The Tomomo configuration file is stored in the Disk\&.
.PP
There are several predefined configuration files and in each of the configuration files there are a set of predefined sequence description with its unit descriptor identifier\&.
.PP
The configuration file identifier is named confid; The sequnce descriptor is named seqid; The selection is achieved with the confid + seqid codes\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum class \fBGantryStatusRegisters::tomoConfig::options_conf\fP\fC [strong]\fP"

.PP
This is the enumeration option code for file configuration\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITOMO_1F \fP\fP
Tomo configuration file 1F\&. 
.TP
\fB\fITOMO_2F \fP\fP
Tomo configuration file 2F\&. 
.TP
\fB\fITOMO_3F \fP\fP
Tomo configuration file 3F\&. 
.TP
\fB\fITOMO_4F \fP\fP
Tomo configuration file 4F\&. 
.TP
\fB\fITOMO_5F \fP\fP
Tomo configuration file 5F\&. 
.TP
\fB\fILEN \fP\fP
.TP
\fB\fIUNDEF \fP\fP
.SS "enum class \fBGantryStatusRegisters::tomoConfig::options_seq\fP\fC [strong]\fP"

.PP
This is the enumeration option code for the particolar sequence in the configuration file 
.br
 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINARROW \fP\fP
Narrow sequence\&. 
.TP
\fB\fIINTERMEDIATE \fP\fP
Intermediate sequence\&. 
.TP
\fB\fIWIDE \fP\fP
Wide seqeunce\&. 
.TP
\fB\fISUPERWIDE \fP\fP
Super-wide sequence\&. 
.TP
\fB\fILEN \fP\fP
.TP
\fB\fIUNDEF \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "delegate void GantryStatusRegisters::tomoConfig::delegate_selection_change (void)"

.PP
This is the delegate of the status_change_event();\&. 
.SS "static bool GantryStatusRegisters::tomoConfig::select (String^ conftag, String^ seqtag)\fC [inline]\fP, \fC [static]\fP"

.PP
This function selects a Tomo configuration sequence based on the confid and seqid identifiers\&. If the selection changes, the \fBselection_change_event()\fP is generated\&.
.PP
\fBParameters\fP
.RS 4
\fIconftag\fP this is the configuration file identifier tag
.br
\fIseqtag\fP this is the sequence identifier tag
.RE
.PP
\fBReturns\fP
.RS 4
tue if the confid + seqid exists
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBoptions_conf\fP GantryStatusRegisters::tomoConfig::confid = \fBoptions_conf::UNDEF\fP\fC [static]\fP, \fC [private]\fP"

.PP
This is the register conf_id\&. 
.SS "\fBoptions_seq\fP GantryStatusRegisters::tomoConfig::seqid = \fBoptions_seq::UNDEF\fP\fC [static]\fP, \fC [private]\fP"

.PP
This is the register sequence_id\&. 
.SS "const array<String^> ^ GantryStatusRegisters::tomoConfig::tags_conf = gcnew array<String^> { 'TOMO_1F', 'TOMO_2F', 'TOMO_3F', 'TOMO_4F', 'TOMO_5F', 'UNDEF' }\fC [static]\fP"

.PP
This is the config id option-tags static array\&. 
.SS "const array<String^> ^ GantryStatusRegisters::tomoConfig::tags_seq = gcnew array<String^> { 'N', 'I', 'W', 'SW', 'UNDEF' }\fC [static]\fP"

.PP
This is the sequence option-tags static array\&. 
.SH "Event Documentation"
.PP 
.SS "\fBdelegate_selection_change\fP^ GantryStatusRegisters::tomoConfig::selection_change_event\fC [static]\fP"

.PP
This event is generated whenver the status of the register is changed\&. Usage: tomoConfigOptions::selection_change_event += gcnew delegate_selection_change(&some_class, some_class::func) 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
