.TH "GantryStatusRegisters::ExposureDataRegister::exposurePulse" 3 "Mon Jul 24 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatusRegisters::ExposureDataRegister::exposurePulse \- Internal class uses to group the exposure data pulses  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexposurePulse\fP (void)"
.br
.RI "This is the creator of the pulse data class\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFilterOptions\fP ^ \fBfilter\fP"
.br
.RI "This is the assigned filter handle\&. "
.ti -1c
.RI "double \fBkV\fP"
.br
.RI "This is the selected kV value\&. "
.ti -1c
.RI "double \fBmAs\fP"
.br
.RI "This is the selected mAs value\&. "
.ti -1c
.RI "bool \fBvalidated\fP"
.br
.RI "This is the flag that validate the use of thhis pulse in a sequence\&. "
.in -1c
.SH "Detailed Description"
.PP 
Internal class uses to group the exposure data pulses 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "GantryStatusRegisters::ExposureDataRegister::exposurePulse::exposurePulse (void)\fC [inline]\fP"

.PP
This is the creator of the pulse data class\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBFilterOptions\fP ^ GantryStatusRegisters::ExposureDataRegister::exposurePulse::filter"

.PP
This is the assigned filter handle\&. 
.SS "double GantryStatusRegisters::ExposureDataRegister::exposurePulse::kV"

.PP
This is the selected kV value\&. 
.SS "double GantryStatusRegisters::ExposureDataRegister::exposurePulse::mAs"

.PP
This is the selected mAs value\&. 
.SS "bool GantryStatusRegisters::ExposureDataRegister::exposurePulse::validated"

.PP
This is the flag that validate the use of thhis pulse in a sequence\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
