.TH "GantryStatusRegisters::CompressionModeOption" 3 "Wed Oct 18 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatusRegisters::CompressionModeOption \- This class handles the Compression behavior during the exposure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBoptions\fP { \fBCMP_KEEP\fP = 0, \fBCMP_RELEASE\fP, \fBCMP_DISABLE\fP, \fBLEN\fP, \fBUNDEF\fP = LEN }"
.br
.RI "This is the enumeration option code  "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBenumType\fP< \fBoptions\fP > ^ \fBValue\fP = gcnew \fBenumType\fP<\fBoptions\fP>(\fBtags\fP)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const cli::array< String^> ^ \fBtags\fP = gcnew cli::array<String^> { 'CMP_KEEP', 'CMP_RELEASE', 'CMP_DISABLE', 'UNDEF'}"
.br
.RI "This is the option-tags static array\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class handles the Compression behavior during the exposure\&. 


.SH "Member Enumeration Documentation"
.PP 
.SS "enum class \fBGantryStatusRegisters::CompressionModeOption::options\fP\fC [strong]\fP"

.PP
This is the enumeration option code  
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICMP_KEEP \fP\fP
Keeps the compression after exposure;\&. 
.TP
\fB\fICMP_RELEASE \fP\fP
Releases the compression after exposure;\&. 
.TP
\fB\fICMP_DISABLE \fP\fP
Disables the Compression check (for exposures without the compression);\&. 
.TP
\fB\fILEN \fP\fP
.TP
\fB\fIUNDEF \fP\fP
.SH "Member Data Documentation"
.PP 
.SS "const cli::array<String^> ^ GantryStatusRegisters::CompressionModeOption::tags = gcnew cli::array<String^> { 'CMP_KEEP', 'CMP_RELEASE', 'CMP_DISABLE', 'UNDEF'}\fC [static]\fP"

.PP
This is the option-tags static array\&. 
.SS "\fBenumType\fP<\fBoptions\fP> ^ GantryStatusRegisters::CompressionModeOption::Value = gcnew \fBenumType\fP<\fBoptions\fP>(\fBtags\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
