.TH "GantryStatusRegisters::SafetyStatusRegister" 3 "Wed Oct 18 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatusRegisters::SafetyStatusRegister
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetCloseDoor\fP (bool stat)"
.br
.ti -1c
.RI "static bool \fBgetCloseDoor\fP (void)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static bool \fBclosed_door\fP = false"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool GantryStatusRegisters::SafetyStatusRegister::getCloseDoor (void)\fC [static]\fP"

.SS "void GantryStatusRegisters::SafetyStatusRegister::setCloseDoor (bool stat)\fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool GantryStatusRegisters::SafetyStatusRegister::closed_door = false\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
