.TH "GantryStatusRegisters::ProjectionOptions" 3 "Wed Jul 26 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatusRegisters::ProjectionOptions \- This is the projection handling class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBoptions\fP { \fBLCC\fP = 0, \fBLFB\fP, \fBLISO\fP, \fBLLM\fP, \fBLLMO\fP, \fBLML\fP, \fBLMLO\fP, \fBLSIO\fP, \fBRCC\fP, \fBRFB\fP, \fBRISO\fP, \fBRLM\fP, \fBRLMO\fP, \fBRML\fP, \fBRMLO\fP, \fBRSIO\fP, \fBLEN\fP, \fBUNDEF\fP = LEN }"
.br
.RI "This is the enumeration option code of the selectable projections\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBenumType\fP< \fBoptions\fP > ^ \fBValue\fP = gcnew \fBenumType\fP<\fBoptions\fP>(\fBtags\fP)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const array< String^> ^ \fBtags\fP = gcnew array<String^> { 'LCC', 'LFB', 'LISO', 'LLM', 'LLMO', 'LML', 'LMLO', 'LSIO', 'RCC', 'RFB', 'RISO', 'RLM', 'RLMO', 'RML', 'RMLO', 'RSIO', 'UNDEF'}"
.br
.RI "This is the option-tags static array\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is the projection handling class\&. 

This class defines the availabe projection options, store the current selected projection and the projection selectable list\&.
.PP
The class provides events related to the data change
.SH "Member Enumeration Documentation"
.PP 
.SS "enum class \fBGantryStatusRegisters::ProjectionOptions::options\fP\fC [strong]\fP"

.PP
This is the enumeration option code of the selectable projections\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILCC \fP\fP
.TP
\fB\fILFB \fP\fP
.TP
\fB\fILISO \fP\fP
.TP
\fB\fILLM \fP\fP
.TP
\fB\fILLMO \fP\fP
.TP
\fB\fILML \fP\fP
.TP
\fB\fILMLO \fP\fP
.TP
\fB\fILSIO \fP\fP
.TP
\fB\fIRCC \fP\fP
.TP
\fB\fIRFB \fP\fP
.TP
\fB\fIRISO \fP\fP
.TP
\fB\fIRLM \fP\fP
.TP
\fB\fIRLMO \fP\fP
.TP
\fB\fIRML \fP\fP
.TP
\fB\fIRMLO \fP\fP
.TP
\fB\fIRSIO \fP\fP
.TP
\fB\fILEN \fP\fP
.TP
\fB\fIUNDEF \fP\fP
.SH "Member Data Documentation"
.PP 
.SS "const array<String^> ^ GantryStatusRegisters::ProjectionOptions::tags = gcnew array<String^> { 'LCC', 'LFB', 'LISO', 'LLM', 'LLMO', 'LML', 'LMLO', 'LSIO', 'RCC', 'RFB', 'RISO', 'RLM', 'RLMO', 'RML', 'RMLO', 'RSIO', 'UNDEF'}\fC [static]\fP"

.PP
This is the option-tags static array\&. 
.SS "\fBenumType\fP<\fBoptions\fP> ^ GantryStatusRegisters::ProjectionOptions::Value = gcnew \fBenumType\fP<\fBoptions\fP>(\fBtags\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
