.TH "GantryStatusRegisters::XrayPushButtonRegister" 3 "Wed Jul 26 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatusRegisters::XrayPushButtonRegister \- This class handles the Xray Push Button activation status and activities  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBoptions\fP { \fBXRAYPUSH_DISABLED\fP = 0, \fBXRAYPUSH_ENABLED\fP = 1, \fBLEN\fP, \fBUNDEF\fP = LEN }"
.br
.RI "Definition of the xray push button enable status\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBisEnabled\fP (void)"
.br
.ti -1c
.RI "static bool \fBisDisabled\fP (void)"
.br
.ti -1c
.RI "static bool \fBsetEnable\fP (void)"
.br
.ti -1c
.RI "static bool \fBsetDisable\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const array< String^> ^ \fBtags\fP = gcnew array<String^> {'OFF', 'ON', 'UNDEF'}"
.br
.RI "Definition of the register tags\&. "
.ti -1c
.RI "static \fBenumType\fP< \fBoptions\fP > ^ \fBValue\fP = gcnew \fBenumType\fP<\fBoptions\fP>(\fBtags\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class handles the Xray Push Button activation status and activities 


.SH "Member Enumeration Documentation"
.PP 
.SS "enum class \fBGantryStatusRegisters::XrayPushButtonRegister::options\fP\fC [strong]\fP"

.PP
Definition of the xray push button enable status\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIXRAYPUSH_DISABLED \fP\fP
XRAY Push Button is enabled\&. 
.TP
\fB\fIXRAYPUSH_ENABLED \fP\fP
XRAY Push Button is disabled\&. 
.TP
\fB\fILEN \fP\fP
.TP
\fB\fIUNDEF \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "static bool GantryStatusRegisters::XrayPushButtonRegister::isDisabled (void)\fC [inline]\fP, \fC [static]\fP"

.SS "static bool GantryStatusRegisters::XrayPushButtonRegister::isEnabled (void)\fC [inline]\fP, \fC [static]\fP"

.SS "static bool GantryStatusRegisters::XrayPushButtonRegister::setDisable ()\fC [inline]\fP, \fC [static]\fP"

.SS "static bool GantryStatusRegisters::XrayPushButtonRegister::setEnable (void)\fC [inline]\fP, \fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const array<String^> ^ GantryStatusRegisters::XrayPushButtonRegister::tags = gcnew array<String^> {'OFF', 'ON', 'UNDEF'}\fC [static]\fP"

.PP
Definition of the register tags\&. 
.SS "\fBenumType\fP<\fBoptions\fP> ^ GantryStatusRegisters::XrayPushButtonRegister::Value = gcnew \fBenumType\fP<\fBoptions\fP>(\fBtags\fP)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
