.TH "GantryStatus::paddleOptions" 3MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatus::paddleOptions
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBoptions\fP { \fBPAD_24x30\fP = 0, \fBPAD_18x24_C\fP, \fBPAD_18x24_L\fP, \fBPAD_18x24_R\fP, \fBPAD_9x21\fP, \fBPAD_10x24\fP, \fBPAD_D75\fP, \fBPAD_BIOP2D\fP, \fBPAD_BIOP3D\fP, \fBPAD_TOMO\fP, \fBPAD_9x9\fP, \fBPAD_UNDETECTED\fP, \fBPAD_UNLOCKED\fP, \fBLEN\fP, \fBUNDEF\fP = LEN }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBstatus_change\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBisValid\fP (String^ val)"
.br
.ti -1c
.RI "static int \fBgetCode\fP (String^ val)"
.br
.ti -1c
.RI "static String ^ \fBgetTag\fP (\fBoptions\fP val)"
.br
.ti -1c
.RI "static bool \fBsetCode\fP (\fBoptions\fP val)"
.br
.ti -1c
.RI "static bool \fBsetTag\fP (String^ val)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const array< String^> ^ \fBtags\fP = gcnew array<String^> { 'PAD_24x30', 'PAD_18x24_C', 'PAD_18x24_L', 'PAD_18x24_R', 'PADCOLLI_9x21', 'PAD_10x24', 'PAD_D75', 'PAD_BIOP2D', 'PAD_BIOP3D', 'PAD_TOMO', 'PAD_9x9', 'PAD_UNDETECTED', 'PAD_UNLOCKED', 'UNDEF' }"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static \fBstatus_change\fP^ \fBstatus_change_event\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBoptions\fP \fBcode\fP = \fBoptions::UNDEF\fP"
.br
.ti -1c
.RI "static String ^ \fBtag\fP = 'UNDEF'"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum class \fBGantryStatus::paddleOptions::options\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPAD_24x30 \fP\fP
.TP
\fB\fIPAD_18x24_C \fP\fP
.TP
\fB\fIPAD_18x24_L \fP\fP
.TP
\fB\fIPAD_18x24_R \fP\fP
.TP
\fB\fIPAD_9x21 \fP\fP
.TP
\fB\fIPAD_10x24 \fP\fP
.TP
\fB\fIPAD_D75 \fP\fP
.TP
\fB\fIPAD_BIOP2D \fP\fP
.TP
\fB\fIPAD_BIOP3D \fP\fP
.TP
\fB\fIPAD_TOMO \fP\fP
.TP
\fB\fIPAD_9x9 \fP\fP
.TP
\fB\fIPAD_UNDETECTED \fP\fP
.TP
\fB\fIPAD_UNLOCKED \fP\fP
.TP
\fB\fILEN \fP\fP
.TP
\fB\fIUNDEF \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "static int GantryStatus::paddleOptions::getCode (String^ val)\fC [inline]\fP, \fC [static]\fP"

.SS "static String ^ GantryStatus::paddleOptions::getTag (\fBoptions\fP val)\fC [inline]\fP, \fC [static]\fP"

.SS "static bool GantryStatus::paddleOptions::isValid (String^ val)\fC [inline]\fP, \fC [static]\fP"

.SS "static bool GantryStatus::paddleOptions::setCode (\fBoptions\fP val)\fC [inline]\fP, \fC [static]\fP"

.SS "static bool GantryStatus::paddleOptions::setTag (String^ val)\fC [inline]\fP, \fC [static]\fP"

.SS "delegate void GantryStatus::paddleOptions::status_change (void)"

.SH "Member Data Documentation"
.PP 
.SS "\fBoptions\fP GantryStatus::paddleOptions::code = \fBoptions::UNDEF\fP\fC [static]\fP, \fC [private]\fP"

.SS "String ^ GantryStatus::paddleOptions::tag = 'UNDEF'\fC [static]\fP, \fC [private]\fP"

.SS "const array<String^> ^ GantryStatus::paddleOptions::tags = gcnew array<String^> { 'PAD_24x30', 'PAD_18x24_C', 'PAD_18x24_L', 'PAD_18x24_R', 'PADCOLLI_9x21', 'PAD_10x24', 'PAD_D75', 'PAD_BIOP2D', 'PAD_BIOP3D', 'PAD_TOMO', 'PAD_9x9', 'PAD_UNDETECTED', 'PAD_UNLOCKED', 'UNDEF' }\fC [static]\fP"

.SH "Event Documentation"
.PP 
.SS "\fBstatus_change\fP^ GantryStatus::paddleOptions::status_change_event\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
