.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/gantry_global_status.h" 3 "Thu May 2 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/gantry_global_status.h
.SH SYNOPSIS
.br
.PP
\fC#include 'math\&.h'\fP
.br
\fC#include 'ValuePopup\&.h'\fP
.br
\fC#include '\&.\&./MOTORS/CanOpenDriver/CanOpenMotor\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGantry\fP"
.br
.ti -1c
.RI "class \fBBiopsy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
