.TH "GantryStatusRegisters::exposurePulse" 3 "Wed Oct 18 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatusRegisters::exposurePulse \- Internal class uses to group the exposure data pulses  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBset\fP (double kv, double mas, String^ filter_tag)"
.br
.RI "This function sets the pulse exposure data content "
.ti -1c
.RI "bool \fBset\fP (double \fBkV\fP, double \fBmAs\fP, \fBFilterOptions::options\fP filter_code)"
.br
.RI "This function sets the exposure data of a given exposure pulse number\&. "
.ti -1c
.RI "void \fBinvalidate\fP (void)"
.br
.RI "This function invalidate the usage of exposure data  "
.ti -1c
.RI "\fBexposurePulse\fP (void)"
.br
.RI "This is the creator of the pulse data class\&.  "
.ti -1c
.RI "bool \fBisValid\fP (void)"
.br
.RI "Returns the Pulse data Validation status  "
.ti -1c
.RI "double \fBgetKv\fP ()"
.br
.RI "Returns the kV of the pulse  "
.ti -1c
.RI "double \fBgetmAs\fP ()"
.br
.RI "Returns the mAs of the pulse  "
.ti -1c
.RI "\fBFilterOptions\fP ^ \fBgetFilter\fP ()"
.br
.RI "Returnrn the filter option of the pulse  "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBFilterOptions\fP ^ \fBfilter\fP"
.br
.RI "This is the assigned filter handle\&. "
.ti -1c
.RI "double \fBkV\fP"
.br
.RI "This is the selected kV value\&. "
.ti -1c
.RI "double \fBmAs\fP"
.br
.RI "This is the selected mAs value\&. "
.ti -1c
.RI "bool \fBvalidated\fP"
.br
.RI "This is the flag that validate the use of thhis pulse in a sequence\&. "
.in -1c
.SH "Detailed Description"
.PP 
Internal class uses to group the exposure data pulses 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "GantryStatusRegisters::exposurePulse::exposurePulse (void)\fC [inline]\fP"

.PP
This is the creator of the pulse data class\&.  
.SH "Member Function Documentation"
.PP 
.SS "\fBFilterOptions\fP ^ GantryStatusRegisters::exposurePulse::getFilter ()\fC [inline]\fP"

.PP
Returnrn the filter option of the pulse  
.PP
\fBReturns\fP
.RS 4
The filter option
.RE
.PP

.SS "double GantryStatusRegisters::exposurePulse::getKv ()\fC [inline]\fP"

.PP
Returns the kV of the pulse  
.PP
\fBReturns\fP
.RS 4
kV value
.RE
.PP

.SS "double GantryStatusRegisters::exposurePulse::getmAs ()\fC [inline]\fP"

.PP
Returns the mAs of the pulse  
.PP
\fBReturns\fP
.RS 4
mAs value
.RE
.PP

.SS "void GantryStatusRegisters::exposurePulse::invalidate (void)\fC [inline]\fP"

.PP
This function invalidate the usage of exposure data  
.SS "bool GantryStatusRegisters::exposurePulse::isValid (void)\fC [inline]\fP"

.PP
Returns the Pulse data Validation status  
.PP
\fBReturns\fP
.RS 4
true if data are valid
.RE
.PP

.SS "bool GantryStatusRegisters::exposurePulse::set (double kV, double mAs, \fBFilterOptions::options\fP filter_code)\fC [inline]\fP"

.PP
This function sets the exposure data of a given exposure pulse number\&. There are a maximum of 4 possible exposure pulses\&.
.PP
\fBParameters\fP
.RS 4
\fIfilter_code\fP This is the code of the filter used in the next exposure pulse
.br
\fIkV\fP kV value of the next exposure pulse [20:640] 
.br
\fImAs\fP mAs value of the next exposure pulse [0:640] 
.RE
.PP
\fBReturns\fP
.RS 4
true if data are accepted
.RE
.PP

.SS "bool GantryStatusRegisters::exposurePulse::set (double kv, double mas, String^ filter_tag)\fC [inline]\fP"

.PP
This function sets the pulse exposure data content 
.PP
\fBParameters\fP
.RS 4
\fIfilter_tag\fP This is the tag of the filter used in the next exposure pulse
.br
\fIkV\fP kV value of the next exposure pulse [20:640] 
.br
\fImAs\fP mAs value of the next exposure pulse [0:640] 
.RE
.PP
\fBReturns\fP
.RS 4
true if data are accepted
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBFilterOptions\fP ^ GantryStatusRegisters::exposurePulse::filter\fC [private]\fP"

.PP
This is the assigned filter handle\&. 
.SS "double GantryStatusRegisters::exposurePulse::kV\fC [private]\fP"

.PP
This is the selected kV value\&. 
.SS "double GantryStatusRegisters::exposurePulse::mAs\fC [private]\fP"

.PP
This is the selected mAs value\&. 
.SS "bool GantryStatusRegisters::exposurePulse::validated\fC [private]\fP"

.PP
This is the flag that validate the use of thhis pulse in a sequence\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
