.TH "C:/Users/marco/Documents/Data/Progetti-GIT/SW/PROGETTO_MAIN_CPU_Z190/MCPU_MASTER/PROJECT_VB/MCPU/MCPU_MASTER/gantry_global_status.h" 3 "Mon Jul 24 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/marco/Documents/Data/Progetti-GIT/SW/PROGETTO_MAIN_CPU_Z190/MCPU_MASTER/PROJECT_VB/MCPU/MCPU_MASTER/gantry_global_status.h
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGantryStatusRegisters::FilterOptions\fP"
.br
.RI "This class implements the Filter selection interface\&. "
.ti -1c
.RI "class \fBGantryStatusRegisters::XrayCompletedRegister\fP"
.br
.RI "This class implements the XRAY completed status register\&."
.ti -1c
.RI "class \fBGantryStatusRegisters::ReadyForExposureRegister\fP"
.br
.RI "This class register handles the REady for exposure conditions\&. "
.ti -1c
.RI "class \fBGantryStatusRegisters::XrayPushButtonRegister\fP"
.br
.RI "This class handles the Xray Push Button activation status and activities "
.ti -1c
.RI "class \fBGantryStatusRegisters::TomoConfigRegister\fP"
.br
.RI "This class implements the Tomo configuration selection options\&. "
.ti -1c
.RI "class \fBGantryStatusRegisters::OperatingStatusRegister\fP"
.br
.RI "This is the Gantry operating status register definition"
.ti -1c
.RI "class \fBGantryStatusRegisters::ProjectionRegister\fP"
.br
.RI "This is the projection handling option class\&. "
.ti -1c
.RI "class \fBGantryStatusRegisters::ComponentRegister\fP"
.br
.RI "This register handle the Component that can be used during the exposure "
.ti -1c
.RI "class \fBGantryStatusRegisters::CollimatorComponentRegister\fP"
.br
.RI "This register handles the component applicable to the collimator "
.ti -1c
.RI "class \fBGantryStatusRegisters::PaddleRegister\fP"
.br
.RI "This register handles the Paddles identifiable by the compressor device "
.ti -1c
.RI "class \fBGantryStatusRegisters::CompressorRegister\fP"
.br
.RI "This is the register handling the compression force and thickness\&. "
.ti -1c
.RI "class \fBGantryStatusRegisters::ErrorRegister\fP"
.br
.RI "This is the Error handling register "
.ti -1c
.RI "class \fBGantryStatusRegisters::ExposureModeRegister\fP"
.br
.RI "This class handles the exposure type status\&. "
.ti -1c
.RI "class \fBGantryStatusRegisters::DetectorTypeRegister\fP"
.br
.RI "This class handles the Detector model selection\&. "
.ti -1c
.RI "class \fBGantryStatusRegisters::CompressionModeRegister\fP"
.br
.RI "This class handles the Compression behavior during the exposure\&. "
.ti -1c
.RI "class \fBGantryStatusRegisters::CollimationModeRegister\fP"
.br
.RI "This class handles the Collimation behavior during the exposure\&. "
.ti -1c
.RI "class \fBGantryStatusRegisters::PatientProtectionRegister\fP"
.br
.RI "This class handles the Usage of the patient protection during the exposure\&. "
.ti -1c
.RI "class \fBGantryStatusRegisters::ArmStatusRegister\fP"
.br
.RI "This is the status register of the Arm motorization\&. "
.ti -1c
.RI "class \fBGantryStatusRegisters::PatientDataRegister\fP"
.br
.RI "This is the class handling the patient name"
.ti -1c
.RI "class \fBGantryStatusRegisters::TrxStatusRegister\fP"
.br
.RI "This class handles the Trx motorization "
.ti -1c
.RI "class \fBGantryStatusRegisters::ExposureDataRegister\fP"
.br
.RI "This register handle the Exposure pulse data info\&. "
.ti -1c
.RI "class \fBGantryStatusRegisters::ExposureDataRegister::exposurePulse\fP"
.br
.RI "Internal class uses to group the exposure data pulses "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBGantryStatusRegisters\fP"
.br
.RI "This is the class implementing the AWS Interface Module "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
