.TH "GantryStatusRegisters::CompressorRegister" 3MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatusRegisters::CompressorRegister \- This is the register handling the compression force and thickness\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBdelegate_compressor_change\fP (void)"
.br
.RI "This is the delegate of the \fBcompressor_change_event()\fP;\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned short \fBgetForce\fP (void)"
.br
.RI "This function returns the current breast compression Force\&. "
.ti -1c
.RI "static unsigned short \fBgetThickness\fP (void)"
.br
.RI "This function returns the breast compression Thickness\&. "
.ti -1c
.RI "static void \fBsetForce\fP (unsigned short force)"
.br
.RI "This function updates the current compression Force\&. "
.ti -1c
.RI "static void \fBsetThickness\fP (unsigned short thick)"
.br
.RI "This function updates the current compression Thickness\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static \fBdelegate_compressor_change\fP^ \fBcompressor_change_event\fP"
.br
.RI "This event is generated whenver the status of the compressor data changes\&. "
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static unsigned short \fBbreast_thickness\fP"
.br
.RI "Compressed breast thickness in mm\&. "
.ti -1c
.RI "static unsigned short \fBcompression_force\fP"
.br
.RI "Compression force in N\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is the register handling the compression force and thickness\&. 


.SH "Member Function Documentation"
.PP 
.SS "delegate void GantryStatusRegisters::CompressorRegister::delegate_compressor_change (void)"

.PP
This is the delegate of the \fBcompressor_change_event()\fP;\&. 
.SS "static unsigned short GantryStatusRegisters::CompressorRegister::getForce (void)\fC [inline]\fP, \fC [static]\fP"

.PP
This function returns the current breast compression Force\&. 
.PP
\fBReturns\fP
.RS 4
The breast compression force in Newtons
.RE
.PP

.SS "static unsigned short GantryStatusRegisters::CompressorRegister::getThickness (void)\fC [inline]\fP, \fC [static]\fP"

.PP
This function returns the breast compression Thickness\&. 
.PP
\fBReturns\fP
.RS 4
The compressed breast thickness in mm
.RE
.PP

.SS "static void GantryStatusRegisters::CompressorRegister::setForce (unsigned short force)\fC [inline]\fP, \fC [static]\fP"

.PP
This function updates the current compression Force\&. If the force is changed then the \fBcompressor_change_event()\fP is generated\&.
.PP
\fBParameters\fP
.RS 4
\fIforce\fP 
.RE
.PP

.SS "static void GantryStatusRegisters::CompressorRegister::setThickness (unsigned short thick)\fC [inline]\fP, \fC [static]\fP"

.PP
This function updates the current compression Thickness\&. If the Thickness is changed then the \fBcompressor_change_event()\fP is generated\&.
.PP
\fBParameters\fP
.RS 4
\fIthick\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "unsigned short GantryStatusRegisters::CompressorRegister::breast_thickness\fC [static]\fP, \fC [private]\fP"

.PP
Compressed breast thickness in mm\&. 
.SS "unsigned short GantryStatusRegisters::CompressorRegister::compression_force\fC [static]\fP, \fC [private]\fP"

.PP
Compression force in N\&. 
.SH "Event Documentation"
.PP 
.SS "\fBdelegate_compressor_change\fP^ GantryStatusRegisters::CompressorRegister::compressor_change_event\fC [static]\fP"

.PP
This event is generated whenver the status of the compressor data changes\&. Usage: \fBCompressorRegister::compressor_change_event\fP += gcnew delegate_compressor_change(&some_class, some_class::func) 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
