.TH "GantryStatus" 3MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatus \- This is the class implementing the AWS Interface Module\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArmStatus\fP"
.br
.ti -1c
.RI "class \fBcolliComponentOptions\fP"
.br
.ti -1c
.RI "class \fBcomponentOptions\fP"
.br
.ti -1c
.RI "class \fBerrorStatus\fP"
.br
.ti -1c
.RI "class \fBfilterOptions\fP"
.br
.ti -1c
.RI "class \fBgantryOperatingStatusOptions\fP"
.br
.ti -1c
.RI "class \fBpaddleOptions\fP"
.br
.ti -1c
.RI "class \fBpatientData\fP"
.br
.ti -1c
.RI "class \fBprojectionOptions\fP"
.br
.ti -1c
.RI "class \fBTrxStatus\fP"
.br
.ti -1c
.RI "class \fBxrayCompletedOptions\fP"
.br
.RI "This class implements the XRAY completed status register\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is the class implementing the AWS Interface Module\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
