.TH "GantryStatusRegisters::CollimationModeRegister" 3MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatusRegisters::CollimationModeRegister \- This class handles the Collimation behavior during the exposure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBoptions\fP { \fBCOLLI_AUTO\fP, \fBCOLLI_24x30\fP, \fBCOLLI_18x24_C\fP, \fBCOLLI_18x24_L\fP, \fBCOLLI_18x24_R\fP, \fBCOLLI_9x21\fP, \fBCOLLI_10x24\fP, \fBCOLLI_PROSTHESIS\fP, \fBCOLLI_D75\fP, \fBCOLLI_BIOP2D\fP, \fBCOLLI_BIOP3D\fP, \fBCOLLI_TOMO\fP, \fBCOLLI_9x9\fP, \fBCOLLI_CUSTOM\fP, \fBLEN\fP, \fBUNDEF\fP = LEN }"
.br
.RI "This is the enumeration option code\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBdelegate_status_change\fP (void)"
.br
.RI "This is the delegate of the \fBstatus_change_event()\fP;\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBoptions\fP \fBgetCode\fP (void)"
.br
.RI "Returns the option code of the register\&. "
.ti -1c
.RI "static String ^ \fBgetTag\fP (void)"
.br
.RI "Returns the option tag of the register\&. "
.ti -1c
.RI "static bool \fBsetCode\fP (\fBoptions\fP val)"
.br
.RI "This function set the register with the option code (and related tag)\&. "
.ti -1c
.RI "static bool \fBsetCode\fP (String^ val)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const array< String^> ^ \fBtags\fP"
.br
.RI "This is the option-tags static array\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static \fBdelegate_status_change\fP^ \fBstatus_change_event\fP"
.br
.RI "This event is generated whenver the status of the register is changed\&. "
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBoptions\fP \fBcode\fP = \fBoptions::UNDEF\fP"
.br
.RI "This is the register option-code\&. "
.ti -1c
.RI "static String ^ \fBtag\fP = 'UNDEF'"
.br
.RI "This is the register tag\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class handles the Collimation behavior during the exposure\&. 

There are several collimation patterns predefined in the system\&.
.PP
This class allows to select the current collimation mode from the available list\&.
.PP
This class allows to handle the collimation codes and tag for other purpose (visualization)\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum class \fBGantryStatusRegisters::CollimationModeRegister::options\fP\fC [strong]\fP"

.PP
This is the enumeration option code\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICOLLI_AUTO \fP\fP
The Exposure uses the Automatic collimation set by the current detected Paddle\&. 
.TP
\fB\fICOLLI_24x30 \fP\fP
Force the 24x30 format\&. 
.TP
\fB\fICOLLI_18x24_C \fP\fP
Force the 18x24 CENTER format\&. 
.TP
\fB\fICOLLI_18x24_L \fP\fP
Force the 18x24 LEFT format\&. 
.TP
\fB\fICOLLI_18x24_R \fP\fP
Force the 18x24 RIGHT format\&. 
.TP
\fB\fICOLLI_9x21 \fP\fP
Force the 9x21(MAG) format\&. 
.TP
\fB\fICOLLI_10x24 \fP\fP
Force the 10x24 format\&. 
.TP
\fB\fICOLLI_PROSTHESIS \fP\fP
Force the PROSTHESIS format\&. 
.TP
\fB\fICOLLI_D75 \fP\fP
Force the D75(MAG) format\&. 
.TP
\fB\fICOLLI_BIOP2D \fP\fP
Force the BIOPSY 2D format\&. 
.TP
\fB\fICOLLI_BIOP3D \fP\fP
Force the BIOPSY STEREO format\&. 
.TP
\fB\fICOLLI_TOMO \fP\fP
Force the TOMO 24x30 format\&. 
.TP
\fB\fICOLLI_9x9 \fP\fP
Force the TOMO 9x9(MAG) format\&. 
.TP
\fB\fICOLLI_CUSTOM \fP\fP
Force the custom format\&. 
.TP
\fB\fILEN \fP\fP
.TP
\fB\fIUNDEF \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "delegate void GantryStatusRegisters::CollimationModeRegister::delegate_status_change (void)"

.PP
This is the delegate of the \fBstatus_change_event()\fP;\&. 
.SS "static \fBoptions\fP GantryStatusRegisters::CollimationModeRegister::getCode (void)\fC [inline]\fP, \fC [static]\fP"

.PP
Returns the option code of the register\&. 
.PP
\fBReturns\fP
.RS 4
the value of the option code 
.RE
.PP

.SS "static String ^ GantryStatusRegisters::CollimationModeRegister::getTag (void)\fC [inline]\fP, \fC [static]\fP"

.PP
Returns the option tag of the register\&. 
.PP
\fBReturns\fP
.RS 4
the value of the Tag 
.RE
.PP

.SS "static bool GantryStatusRegisters::CollimationModeRegister::setCode (\fBoptions\fP val)\fC [inline]\fP, \fC [static]\fP"

.PP
This function set the register with the option code (and related tag)\&. The register is updated with the option code and related tag and, in case of value change, the \fBstatus_change_event()\fP is generated\&.
.PP
\fBParameters\fP
.RS 4
\fIval\fP this is the option-code to be set
.RE
.PP
\fBReturns\fP
.RS 4
true if success or false if the code doesn't exist
.RE
.PP

.SS "static bool GantryStatusRegisters::CollimationModeRegister::setCode (String^ val)\fC [inline]\fP, \fC [static]\fP"
This function set the register with the option tag (and related code)\&.
.PP
The register is updated with the tag and the related option code and, in case of value change, the \fBstatus_change_event()\fP is generated\&.
.PP
\fBParameters\fP
.RS 4
\fIval\fP this is the tag to be set
.RE
.PP
\fBReturns\fP
.RS 4
true if success or false if the code doesn't exist
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBoptions\fP GantryStatusRegisters::CollimationModeRegister::code = \fBoptions::UNDEF\fP\fC [static]\fP, \fC [private]\fP"

.PP
This is the register option-code\&. 
.SS "String ^ GantryStatusRegisters::CollimationModeRegister::tag = 'UNDEF'\fC [static]\fP, \fC [private]\fP"

.PP
This is the register tag\&. 
.SS "const array<String^> ^ GantryStatusRegisters::CollimationModeRegister::tags\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
= gcnew array<String^>  { "COLLI_AUTO", "COLLI_24x30", "COLLI_18x24_C", "COLLI_18x24_L", 
                                                                    "COLLI_18x24_R", "COLLI_9x21", "COLLI_10x24", "COLLI_PROSTHESIS", 
                                                                    "COLLI_D75", "COLLI_BIOP2D", "COLLI_BIOP3D", "COLLI_TOMO", 
                                                                    "COLLI_9x9", "COLLI_CUSTOM", "UNDEF"}
.fi

.PP
This is the option-tags static array\&. 
.SH "Event Documentation"
.PP 
.SS "\fBdelegate_status_change\fP^ GantryStatusRegisters::CollimationModeRegister::status_change_event\fC [static]\fP"

.PP
This event is generated whenver the status of the register is changed\&. Usage: \fBCollimationModeRegister::status_change_event\fP += gcnew delegate_status_change(&some_class, some_class::func) 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
