.TH "GantryStatus::patientData" 3MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatus::patientData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetName\fP (String^ val)"
.br
.ti -1c
.RI "static String ^ \fBgetName\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static String ^ \fBpatient_name\fP = ''"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static String ^ GantryStatus::patientData::getName ()\fC [inline]\fP, \fC [static]\fP"

.SS "static void GantryStatus::patientData::setName (String^ val)\fC [inline]\fP, \fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "String ^ GantryStatus::patientData::patient_name = ''\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
