.TH "GantryStatusRegisters::TubeDataRegister" 3MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatusRegisters::TubeDataRegister \- This class handles the Xray Tybe data and setting\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned char \fBgetAnode\fP (void)"
.br
.RI "This function returns the cumulated anode Hu\&. "
.ti -1c
.RI "static unsigned char \fBgetBulb\fP (void)"
.br
.RI "This function returns the cumulated bulb's heat\&. "
.ti -1c
.RI "static unsigned char \fBgetStator\fP (void)"
.br
.RI "This function returns the cumulated stator's heat\&. "
.ti -1c
.RI "static unsigned short \fBgetExposures\fP (void)"
.br
.RI "This function returns the available number of exposure that it ishould be possible before to stop for temperature issues\&. "
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static unsigned char \fBanodeHu\fP = 0"
.br
.RI "Cumulated Anode HU %\&. "
.ti -1c
.RI "static unsigned char \fBbulbHeat\fP = 0"
.br
.RI "Cumulated Bulb Heat %\&. "
.ti -1c
.RI "static unsigned char \fBstatorHeat\fP = 0"
.br
.RI "Cumulated Stator Heat %\&. "
.ti -1c
.RI "static unsigned short \fBavailableExposure\fP = 0xFFFF"
.br
.RI "Estimated number of available exposure\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class handles the Xray Tybe data and setting\&. 

<> 
.SH "Member Function Documentation"
.PP 
.SS "static unsigned char GantryStatusRegisters::TubeDataRegister::getAnode (void)\fC [inline]\fP, \fC [static]\fP"

.PP
This function returns the cumulated anode Hu\&. 
.PP
\fBReturns\fP
.RS 4
Anode Hu in % respect the maximum
.RE
.PP

.SS "static unsigned char GantryStatusRegisters::TubeDataRegister::getBulb (void)\fC [inline]\fP, \fC [static]\fP"

.PP
This function returns the cumulated bulb's heat\&. 
.PP
\fBReturns\fP
.RS 4
Bulb's heat in % respect the maximum
.RE
.PP

.SS "static unsigned short GantryStatusRegisters::TubeDataRegister::getExposures (void)\fC [inline]\fP, \fC [static]\fP"

.PP
This function returns the available number of exposure that it ishould be possible before to stop for temperature issues\&. 
.PP
\fBReturns\fP
.RS 4
Number of available exposures
.RE
.PP

.SS "static unsigned char GantryStatusRegisters::TubeDataRegister::getStator (void)\fC [inline]\fP, \fC [static]\fP"

.PP
This function returns the cumulated stator's heat\&. 
.PP
\fBReturns\fP
.RS 4
Stator's heat in % respect the maximum
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "unsigned char GantryStatusRegisters::TubeDataRegister::anodeHu = 0\fC [static]\fP, \fC [private]\fP"

.PP
Cumulated Anode HU %\&. 
.SS "unsigned short GantryStatusRegisters::TubeDataRegister::availableExposure = 0xFFFF\fC [static]\fP, \fC [private]\fP"

.PP
Estimated number of available exposure\&. 
.SS "unsigned char GantryStatusRegisters::TubeDataRegister::bulbHeat = 0\fC [static]\fP, \fC [private]\fP"

.PP
Cumulated Bulb Heat %\&. 
.SS "unsigned char GantryStatusRegisters::TubeDataRegister::statorHeat = 0\fC [static]\fP, \fC [private]\fP"

.PP
Cumulated Stator Heat %\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
