.TH "GantryStatusRegisters::errorStatus" 3MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatusRegisters::errorStatus
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBisError\fP (void)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static bool \fBerror_status\fP = false"
.br
.ti -1c
.RI "static array< int > ^ \fBerror_code_list\fP = gcnew array<int> {}"
.br
.ti -1c
.RI "static array< String^> ^ \fBerror_string_list\fP = gcnew array<String^> {''}"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static bool GantryStatusRegisters::errorStatus::isError (void)\fC [inline]\fP, \fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "array<int> ^ GantryStatusRegisters::errorStatus::error_code_list = gcnew array<int> {}\fC [static]\fP, \fC [private]\fP"

.SS "bool GantryStatusRegisters::errorStatus::error_status = false\fC [static]\fP, \fC [private]\fP"

.SS "array<String^> ^ GantryStatusRegisters::errorStatus::error_string_list = gcnew array<String^> {''}\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
