.TH "GantryStatusRegisters::ExposureDataRegister" 3 "Wed Jul 26 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GantryStatusRegisters::ExposureDataRegister \- This register handle the Exposure pulse data info\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBExposureCompletedOptions\fP ^ \fBgetExposureComplete\fP (void)"
.br
.ti -1c
.RI "static \fBexposurePulse\fP ^ \fBgetPulse\fP (int i)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static array< \fBexposurePulse\fP^> ^ \fBpulses\fP = gcnew array<\fBexposurePulse\fP^>{gcnew \fBexposurePulse\fP, gcnew \fBexposurePulse\fP, gcnew \fBexposurePulse\fP, gcnew \fBexposurePulse\fP}"
.br
.RI "Stores the array of data pulses\&. "
.ti -1c
.RI "static \fBExposureCompletedOptions\fP ^ \fBexposure_complete\fP = gcnew \fBExposureCompletedOptions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This register handle the Exposure pulse data info\&. 

The Exposure data of the exposure sequence is stored into this register\&. <> 
.SH "Member Function Documentation"
.PP 
.SS "static \fBExposureCompletedOptions\fP ^ GantryStatusRegisters::ExposureDataRegister::getExposureComplete (void)\fC [inline]\fP, \fC [static]\fP"

.SS "static \fBexposurePulse\fP ^ GantryStatusRegisters::ExposureDataRegister::getPulse (int i)\fC [inline]\fP, \fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBExposureCompletedOptions\fP ^ GantryStatusRegisters::ExposureDataRegister::exposure_complete = gcnew \fBExposureCompletedOptions\fP\fC [static]\fP, \fC [private]\fP"

.SS "array<\fBexposurePulse\fP^> ^ GantryStatusRegisters::ExposureDataRegister::pulses = gcnew array<\fBexposurePulse\fP^>{gcnew \fBexposurePulse\fP, gcnew \fBexposurePulse\fP, gcnew \fBexposurePulse\fP, gcnew \fBexposurePulse\fP}\fC [static]\fP, \fC [private]\fP"

.PP
Stores the array of data pulses\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
