.TH "GlobalObjects" 3 "Wed Jul 26 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GlobalObjects
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gantry_global_status\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Object ^ \fBpAws\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Object ^ GlobalObjects::pAws\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
