.TH "GUI_Module" 3 "Fri Dec 15 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUI_Module \- Gantry GUI modules
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBConfirmation Window Management Module\fP"
.br
.RI ""
.ti -1c
.RI "\fBError Window Management Module\fP"
.br
.RI ""
.ti -1c
.RI "\fBIDLE Status Window Management Module\fP"
.br
.RI "This module implements the features of the \fBGantry\fP IDLE status "
.ti -1c
.RI "\fBStartup GUI Module\fP"
.br
.RI ""
.ti -1c
.RI "\fBOperating Status Window Management Module\fP"
.br
.RI ""
.ti -1c
.RI "\fBProjection Selection Window Management Module\fP"
.br
.RI ""
.ti -1c
.RI "\fBService Window Management Module\fP"
.br
.RI "This module implements the features of the \fBGantry\fP Service Status "
.in -1c
.SH "Detailed Description"
.PP 



.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
