.TH "IDLESTATUS" 3 "Mon Dec 4 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IDLESTATUS
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBbatteryStatus\fP"
.br
.ti -1c
.RI "struct \fBtubeStatus\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBbatteryStatus\fP \fBIDLESTATUS::battery\fP"
.br
.ti -1c
.RI "   \fBtubeStatus\fP \fBIDLESTATUS::tube\fP"
.br
.ti -1c
.RI "   bool \fBIDLESTATUS::powerdown\fP"
.br
.ti -1c
.RI "   bool \fBIDLESTATUS::closed_door\fP"
.br
.ti -1c
.RI "   bool \fBIDLESTATUS::aws_connected\fP"
.br
.ti -1c
.RI "   bool \fBIDLESTATUS::peripherals_connected\fP"
.br
.ti -1c
.RI "} \fBRegisters\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "bool IDLESTATUS::aws_connected"

.SS "\fBbatteryStatus\fP IDLESTATUS::battery"

.SS "bool IDLESTATUS::closed_door"

.SS "bool IDLESTATUS::peripherals_connected"

.SS "bool IDLESTATUS::powerdown"

.SS "struct  { \&.\&.\&. }  IDLESTATUS::Registers\fC [static]\fP"

.SS "\fBtubeStatus\fP IDLESTATUS::tube"

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
