.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/WINDOWS/MainForm.h" 3 "Mon May 13 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/WINDOWS/MainForm.h
.SH SYNOPSIS
.br
.PP
\fC#include <Windows\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCppCLRWinFormsProject::MainForm\fP"
.br
.RI "Summary for \fBMainForm\fP  "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCppCLRWinFormsProject\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "double \fBdtempo\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "double dtempo\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
