.TH "PCB303_Interface" 3 "Mon May 13 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCB303_Interface \- Application Interface
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPCB303::formatBlades\fP"
.br
.RI "This class provides a contenitor for a CALIBRATION blade setup"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPCB303::PCB303\fP ()"
.br
.RI "\fBPCB303\fP Class constructor\&. "
.in -1c
.in +1c
.ti -1c
.RI "static void \fBPCB303::setAutoCollimationMode\fP (void)"
.br
.RI "This function sets the format collimation to AUTO mode\&. "
.ti -1c
.RI "static void \fBPCB303::setOpenCollimationMode\fP (void)"
.br
.RI "This function sets the format collimation to OPEN mode\&. "
.ti -1c
.RI "static void \fBPCB303::setCalibrationCollimationMode\fP (\fBformatBlades\fP^ blades)"
.br
.RI "This function sets the format collimation to CALIBRATION mode\&. "
.ti -1c
.RI "static void \fBPCB303::setTomoCollimationMode\fP (void)"
.br
.RI "This function activates the Tomo collimation mode\&. "
.ti -1c
.RI "static void \fBPCB303::setCustomCollimationMode\fP (\fBColliStandardSelections\fP custom)"
.br
.RI "This function sets the format collimation to CUSTOM mode\&. "
.ti -1c
.RI "static void \fBPCB303::resetFaults\fP (void)"
.br
.RI "In case of collimation fault condition, this function starts a new collimation attempt\&. "
.ti -1c
.RI "static bool \fBPCB303::isValidCollimationFormat\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "static bool PCB303::isValidCollimationFormat (void)\fC [inline]\fP, \fC [static]\fP"

.SS "PCB303::PCB303 ()\fC [inline]\fP"

.PP
\fBPCB303\fP Class constructor\&. The construction initializes several internal variables\&. The constructor call the base class setting the address of the controlled device\&.
.PP
As soon as the base class is initialized, the communication process starts and the device is initialized with \fBconfigurationLoop()\fP routine\&.
.SS "void PCB303::resetFaults (void)\fC [static]\fP"

.PP
In case of collimation fault condition, this function starts a new collimation attempt\&. This functions resets the Application fault condition for the format collimation\&.
.PP
The Fault is reset ONLY in the application not in the device\&. After the fault should be reset, the application can try once more to set the format collimation\&.
.SS "void PCB303::setAutoCollimationMode (void)\fC [static]\fP"

.PP
This function sets the format collimation to AUTO mode\&. 
.SS "void PCB303::setCalibrationCollimationMode (\fBformatBlades\fP^ blades)\fC [static]\fP"

.PP
This function sets the format collimation to CALIBRATION mode\&. This command sets the CALIBRATION collimation mode 
.PP
\fBParameters\fP
.RS 4
\fIblades\fP This is the register containing the blades values
.RE
.PP

.SS "void PCB303::setCustomCollimationMode (\fBColliStandardSelections\fP custom)\fC [static]\fP"

.PP
This function sets the format collimation to CUSTOM mode\&. This function sets the Custom Collimation mode
.PP
\fBParameters\fP
.RS 4
\fIcustom\fP This is a valid collimation code
.RE
.PP

.SS "void PCB303::setOpenCollimationMode (void)\fC [static]\fP"

.PP
This function sets the format collimation to OPEN mode\&. 
.SS "void PCB303::setTomoCollimationMode (void)\fC [static]\fP"

.PP
This function activates the Tomo collimation mode\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
