.TH "PCB303::formatBlades" 3 "Fri Dec 15 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCB303::formatBlades \- This class provides a contenitor for a CALIBRATION blade setup 

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PCB303\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBformatBlades\fP (unsigned short ft, unsigned short bk, unsigned short lt, unsigned short rt, unsigned short tp)"
.br
.RI "This is the constructor to directly assigne the value of the blades positions  "
.ti -1c
.RI "\fBformatBlades\fP ()"
.br
.RI "This is the constructor of an OPEN blades  "
.ti -1c
.RI "void \fBcopy\fP (\fBformatBlades\fP^ b)"
.br
.RI "This is the function to copy a Blade setting  "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBfront\fP"
.br
.RI "Front blade position\&. "
.ti -1c
.RI "unsigned short \fBback\fP"
.br
.RI "back blade position "
.ti -1c
.RI "unsigned short \fBleft\fP"
.br
.RI "Left blade position\&. "
.ti -1c
.RI "unsigned short \fBright\fP"
.br
.RI "Right blade position\&. "
.ti -1c
.RI "unsigned short \fBtrap\fP"
.br
.RI "Trap blade position\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class provides a contenitor for a CALIBRATION blade setup
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PCB303::formatBlades::formatBlades (unsigned short ft, unsigned short bk, unsigned short lt, unsigned short rt, unsigned short tp)\fC [inline]\fP"

.PP
This is the constructor to directly assigne the value of the blades positions  
.PP
\fBParameters\fP
.RS 4
\fIft\fP front blade
.br
\fIbk\fP back blade
.br
\fIlt\fP left blade
.br
\fIrt\fP right blade
.br
\fItp\fP trap blade
.RE
.PP

.SS "PCB303::formatBlades::formatBlades ()\fC [inline]\fP"

.PP
This is the constructor of an OPEN blades  
.SH "Member Function Documentation"
.PP 
.SS "void PCB303::formatBlades::copy (\fBformatBlades\fP^ b)\fC [inline]\fP"

.PP
This is the function to copy a Blade setting  
.PP
\fBParameters\fP
.RS 4
\fIb\fP Handle of a Blade to be copied
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "unsigned short PCB303::formatBlades::back"

.PP
back blade position 
.SS "unsigned short PCB303::formatBlades::front"

.PP
Front blade position\&. 
.SS "unsigned short PCB303::formatBlades::left"

.PP
Left blade position\&. 
.SS "unsigned short PCB303::formatBlades::right"

.PP
Right blade position\&. 
.SS "unsigned short PCB303::formatBlades::trap"

.PP
Trap blade position\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
