.TH "PCB315_Protocol" 3 "Mon Dec 4 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCB315_Protocol \- Protocol Implementation
.PP
 \- This section implements the internal module data and structures in order to implement the protocol detail specifications related to the \fBPCB315\fP board\&.  

.SH SYNOPSIS
.br
.PP

.in +1c
.ti -1c
.RI "#define \fBPCB315_ERROR_BULB_LOW\fP(reg)   (reg\->d2 & 0x1)"
.br
.RI "This is the Bulb sensor low level\&. "
.ti -1c
.RI "#define \fBPCB315_ERROR_BULB_SHORT\fP(reg)   (reg\->d2 & 0x2)"
.br
.RI "This is the Bulb sensor connetions open\&. "
.ti -1c
.RI "#define \fBPCB315_ERROR_BULB_HIGH\fP(reg)   (reg\->d2 & 0x4)"
.br
.RI "This is the Bulb sensor high temperature\&. "
.ti -1c
.RI "#define \fBPCB315_ERROR_STATOR_LOW\fP(reg)   (reg\->d2 & 0x8)"
.br
.RI "This is the Bulb sensor low level\&. "
.ti -1c
.RI "#define \fBPCB315_ERROR_STATOR_SHORT\fP(reg)   (reg\->d2 & 0x10)"
.br
.RI "This is the Bulb sensor connetions open\&. "
.ti -1c
.RI "#define \fBPCB315_ERROR_STATOR_HIGH\fP(reg)   (reg\->d2 & 0x20)"
.br
.RI "This is the Bulb sensor high temperature\&. "
.ti -1c
.RI "#define \fBPCB315_ERROR_FILTER_SELECTION\fP(reg)   (reg\->d2 & 0x40)"
.br
.RI "This is the Filter selection error\&. "
.ti -1c
.RI "#define \fBPCB315_GET_SYSTEM_FILTER\fP(reg)   (unsigned char) (reg\->d0)"
.br
.RI "This macro returns the FILTER byte of the SYSTEM register\&. "
.ti -1c
.RI "#define \fBPCB315_GET_SYSTEM_STATOR\fP(reg)   (unsigned char) (reg\->d1)"
.br
.RI "This macro returns the STATOR byte of the SYSTEM register\&. "
.ti -1c
.RI "#define \fBPCB315_GET_SYSTEM_BULB\fP(reg)   (unsigned char) (reg\->d2)"
.br
.RI "This macro returns the BULB byte of the SYSTEM register\&. "
.ti -1c
.RI "#define \fBPCB315_GET_SYSTEM_FLAGS\fP(reg)   (unsigned char) (reg\->d3)"
.br
.RI "This macro returns the FLAGS byte of the SYSTEM register\&. "
.ti -1c
.RI "#define \fBPCB315_GET_LIGHT_FLAG\fP(flags)   ((flags) & 0x1)"
.br
.RI "This macro returns the Light On flag\&. "
.ti -1c
.RI "#define \fBPCB315_GET_ERROR_FLAG\fP(flags)   ((flags) & 0x80)"
.br
.RI "This macro returns the status of the Error present condition\&. "
.ti -1c
.RI "#define \fBPCB315_WRITE_FILTER1_REGISTER\fP(val)   (System::Byte) ParamRegisters::FILTER1_PARAM_REGISTER,(System::Byte) (val&0xFF), (System::Byte) ((val>>8)&0xFF),(System::Byte) 0, (System::Byte) 0"
.br
.ti -1c
.RI "#define \fBPCB315_WRITE_FILTER2_REGISTER\fP(val)   (System::Byte) ParamRegisters::FILTER2_PARAM_REGISTER,(System::Byte) (val&0xFF), (System::Byte) ((val>>8)&0xFF),(System::Byte) 0, (System::Byte) 0"
.br
.ti -1c
.RI "#define \fBPCB315_WRITE_FILTER3_REGISTER\fP(val)   (System::Byte) ParamRegisters::FILTER3_PARAM_REGISTER,(System::Byte) (val&0xFF), (System::Byte) ((val>>8)&0xFF),(System::Byte) 0, (System::Byte) 0"
.br
.ti -1c
.RI "#define \fBPCB315_WRITE_FILTER4_REGISTER\fP(val)   (System::Byte) ParamRegisters::FILTER4_PARAM_REGISTER,(System::Byte) (val&0xFF), (System::Byte) ((val>>8)&0xFF),(System::Byte) 0, (System::Byte) 0"
.br
.ti -1c
.RI "#define \fBPCB315_WRITE_MIRROR_REGISTER\fP(val)   (System::Byte) ParamRegisters::MIRROR_PARAM_REGISTER,(System::Byte) (val&0xFF), (System::Byte) 0,(System::Byte) 0, (System::Byte) 0"
.br
.ti -1c
.RI "#define \fBPCB315_WRITE_POWERLIGHT_REGISTER\fP(val)   (System::Byte) ParamRegisters::POWERLIGHT_PARAM_REGISTER,(System::Byte) (val&0xFF), (System::Byte) 0,(System::Byte) 0, (System::Byte) 0"
.br
.ti -1c
.RI "#define \fBPCB315_SET_POSITIONER_COMMAND\fP(cmd)   (System::Byte) Commandregister::SET_POSITIONER_COMMAND, (System::Byte) (cmd),(System::Byte) 0,(System::Byte) 0,(System::Byte) 0"
.br
.RI "This is the SET_POSITIONER_COMMAND byte frame\&. "
.ti -1c
.RI "#define \fBPCB315_SET_LIGH_COMMAND\fP(cmd)   (System::Byte) Commandregister::SET_LIGHT, (System::Byte) (cmd),(System::Byte) 0,(System::Byte) 0,(System::Byte) 0"
.br
.RI "This is the SET_POSITIONER_COMMAND byte frame\&. "
.in -1c
.SH "Detailed Description"
.PP 
This section implements the internal module data and structures in order to implement the protocol detail specifications related to the \fBPCB315\fP board\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define PCB315_ERROR_BULB_HIGH(reg)   (reg\->d2 & 0x4)"

.PP
This is the Bulb sensor high temperature\&. 
.SS "#define PCB315_ERROR_BULB_LOW(reg)   (reg\->d2 & 0x1)"

.PP
This is the Bulb sensor low level\&. <> 
.SS "#define PCB315_ERROR_BULB_SHORT(reg)   (reg\->d2 & 0x2)"

.PP
This is the Bulb sensor connetions open\&. 
.SS "#define PCB315_ERROR_FILTER_SELECTION(reg)   (reg\->d2 & 0x40)"

.PP
This is the Filter selection error\&. 
.SS "#define PCB315_ERROR_STATOR_HIGH(reg)   (reg\->d2 & 0x20)"

.PP
This is the Bulb sensor high temperature\&. 
.SS "#define PCB315_ERROR_STATOR_LOW(reg)   (reg\->d2 & 0x8)"

.PP
This is the Bulb sensor low level\&. 
.SS "#define PCB315_ERROR_STATOR_SHORT(reg)   (reg\->d2 & 0x10)"

.PP
This is the Bulb sensor connetions open\&. 
.SS "#define PCB315_GET_ERROR_FLAG(flags)   ((flags) & 0x80)"

.PP
This macro returns the status of the Error present condition\&. 
.SS "#define PCB315_GET_LIGHT_FLAG(flags)   ((flags) & 0x1)"

.PP
This macro returns the Light On flag\&. 
.SS "#define PCB315_GET_SYSTEM_BULB(reg)   (unsigned char) (reg\->d2)"

.PP
This macro returns the BULB byte of the SYSTEM register\&. 
.SS "#define PCB315_GET_SYSTEM_FILTER(reg)   (unsigned char) (reg\->d0)"

.PP
This macro returns the FILTER byte of the SYSTEM register\&. 
.SS "#define PCB315_GET_SYSTEM_FLAGS(reg)   (unsigned char) (reg\->d3)"

.PP
This macro returns the FLAGS byte of the SYSTEM register\&. 
.SS "#define PCB315_GET_SYSTEM_STATOR(reg)   (unsigned char) (reg\->d1)"

.PP
This macro returns the STATOR byte of the SYSTEM register\&. 
.SS "#define PCB315_SET_LIGH_COMMAND(cmd)   (System::Byte) Commandregister::SET_LIGHT, (System::Byte) (cmd),(System::Byte) 0,(System::Byte) 0,(System::Byte) 0"

.PP
This is the SET_POSITIONER_COMMAND byte frame\&. 
.SS "#define PCB315_SET_POSITIONER_COMMAND(cmd)   (System::Byte) Commandregister::SET_POSITIONER_COMMAND, (System::Byte) (cmd),(System::Byte) 0,(System::Byte) 0,(System::Byte) 0"

.PP
This is the SET_POSITIONER_COMMAND byte frame\&. 
.SS "#define PCB315_WRITE_FILTER1_REGISTER(val)   (System::Byte) ParamRegisters::FILTER1_PARAM_REGISTER,(System::Byte) (val&0xFF), (System::Byte) ((val>>8)&0xFF),(System::Byte) 0, (System::Byte) 0"

.SS "#define PCB315_WRITE_FILTER2_REGISTER(val)   (System::Byte) ParamRegisters::FILTER2_PARAM_REGISTER,(System::Byte) (val&0xFF), (System::Byte) ((val>>8)&0xFF),(System::Byte) 0, (System::Byte) 0"

.SS "#define PCB315_WRITE_FILTER3_REGISTER(val)   (System::Byte) ParamRegisters::FILTER3_PARAM_REGISTER,(System::Byte) (val&0xFF), (System::Byte) ((val>>8)&0xFF),(System::Byte) 0, (System::Byte) 0"

.SS "#define PCB315_WRITE_FILTER4_REGISTER(val)   (System::Byte) ParamRegisters::FILTER4_PARAM_REGISTER,(System::Byte) (val&0xFF), (System::Byte) ((val>>8)&0xFF),(System::Byte) 0, (System::Byte) 0"

.SS "#define PCB315_WRITE_MIRROR_REGISTER(val)   (System::Byte) ParamRegisters::MIRROR_PARAM_REGISTER,(System::Byte) (val&0xFF), (System::Byte) 0,(System::Byte) 0, (System::Byte) 0"

.SS "#define PCB315_WRITE_POWERLIGHT_REGISTER(val)   (System::Byte) ParamRegisters::POWERLIGHT_PARAM_REGISTER,(System::Byte) (val&0xFF), (System::Byte) 0,(System::Byte) 0, (System::Byte) 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
