.TH "PCB326" 3 "Mon Dec 4 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCB326
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PCB326\&.h>\fP
.PP
Inherits \fBCanDeviceProtocol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPCB326\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPCB326\fP ^ \fBdevice\fP = gcnew \fBPCB326\fP()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrunningLoop\fP (void) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PCB326::PCB326 ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void PCB326::runningLoop (void)\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBCanDeviceProtocol\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPCB326\fP ^ PCB326::device = gcnew \fBPCB326\fP()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
