.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS/CanOpenDriver/pd4_od.h" 3 "Mon May 13 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS/CanOpenDriver/pd4_od.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CanOpenMotor\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPD4_MOTOR_DI1\fP   0x00010000"
.br
.ti -1c
.RI "#define \fBPD4_MOTOR_DI2\fP   0x00020000"
.br
.ti -1c
.RI "#define \fBPD4_MOTOR_DI3\fP   0x00040000"
.br
.ti -1c
.RI "#define \fBPD4_MOTOR_DI4\fP   0x00080000"
.br
.ti -1c
.RI "#define \fBPD4_MOTOR_DI5\fP   0x00100000"
.br
.ti -1c
.RI "#define \fBPD4_MOTOR_DI6\fP   0x00200000"
.br
.ti -1c
.RI "#define \fBPD4_MOTOR_DO1\fP   0x00010000"
.br
.ti -1c
.RI "#define \fBPD4_MOTOR_DO2\fP   0x00020000"
.br
.ti -1c
.RI "#define \fBZERO_SETTING_CTRL_INIT\fP   0x0270,0x0000"
.br
.ti -1c
.RI "#define \fBZERO_SETTING_START\fP   0x0270,0x0010"
.br
.ti -1c
.RI "#define \fBZERO_SETTING_STOP\fP   0x0270,0x0010"
.br
.ti -1c
.RI "#define \fBZERO_STAT_PERFORMED\fP   0x3400,0x0000"
.br
.ti -1c
.RI "#define \fBZERO_STAT_INTERRUPTED\fP   0x3400,0x0400"
.br
.ti -1c
.RI "#define \fBZERO_STAT_CONFIRMED\fP   0x3400,0x1000"
.br
.ti -1c
.RI "#define \fBZERO_STAT_COMPLETED\fP   0x3400,0x1400"
.br
.ti -1c
.RI "#define \fBZERO_STAT_ERROR_RUN\fP   0x3400,0x2000"
.br
.ti -1c
.RI "#define \fBZERO_STAT_ERROR_IDL\fP   0x3400,0x2400"
.br
.ti -1c
.RI "#define \fBPOSITION_SETTING_CTRL_INIT_MASK\fP   0x0370"
.br
.ti -1c
.RI "#define \fBPOSITION_SETTING_CTRL_INIT_VAL\fP   0x0020"
.br
.ti -1c
.RI "#define \fBPOSITION_TRIGGER_SETTING_CTRL_INIT\fP   0x0370, 0x0000"
.br
.ti -1c
.RI "#define \fBPOSITION_SETTING_START_MASK\fP   0x0370"
.br
.ti -1c
.RI "#define \fBPOSITION_SETTING_START_VAL\fP   0x0030"
.br
.ti -1c
.RI "#define \fBOD_1001_00\fP   0x1001, 0x00, ODRegister::SDODataDimension::R1B"
.br
.ti -1c
.RI "#define \fBOD_1001_00_GENERAL_ERROR\fP   0x1"
.br
.ti -1c
.RI "#define \fBOD_1001_00_I_ERROR\fP   0x2"
.br
.ti -1c
.RI "#define \fBOD_1001_00_VOLTAGE_ERROR\fP   0x4"
.br
.ti -1c
.RI "#define \fBOD_1001_00_TEMP_ERROR\fP   0x8"
.br
.ti -1c
.RI "#define \fBOD_1001_00_COM_ERROR\fP   0x10"
.br
.ti -1c
.RI "#define \fBOD_1001_00_PROFILE_ERROR\fP   0x20"
.br
.ti -1c
.RI "#define \fBOD_1001_00_RESERVED_ERROR\fP   0x40"
.br
.ti -1c
.RI "#define \fBOD_1001_00_MANUFACT_ERROR\fP   0x80"
.br
.ti -1c
.RI "#define \fBOD_1003_01\fP   0x1003, 0x01, ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_1010_01\fP   0x1010, 0x01, ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_1010_02\fP   0x1010, 0x02, ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_1010_03\fP   0x1010, 0x03, ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_1010_04\fP   0x1010, 0x04, ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_1010_05\fP   0x1010, 0x05, ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_1010_06\fP   0x1010, 0x06, ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_SAVE_CODE\fP   0x65766173"
.br
.ti -1c
.RI "#define \fBOD_SAVE_ENABLED\fP   0x1"
.br
.ti -1c
.RI "#define \fBOD_SAVE_DISABLED\fP   0"
.br
.ti -1c
.RI "#define \fBOD_2700_01\fP   0x2700, 0x01 ,ODRegister::SDODataDimension::R1B"
.br
.ti -1c
.RI "#define \fBOD_2700_02\fP   0x2700, 0x02 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_2700_03\fP   0x2700, 0x03 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_2700_04\fP   0x2700, 0x04 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_2700_05\fP   0x2700, 0x05 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_2700_06\fP   0x2700, 0x06 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_2700_07\fP   0x2700, 0x07 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_2700_08\fP   0x2700, 0x08 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_2700_09\fP   0x2700, 0x09 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBCONFIG_USER_PARAM\fP   \fBOD_2700_02\fP"
.br
.ti -1c
.RI "#define \fBNANOJ_USER_PARAM\fP   \fBOD_2700_03\fP"
.br
.ti -1c
.RI "#define \fBRESET_USER_PARAM\fP   \fBOD_2700_04\fP"
.br
.ti -1c
.RI "#define \fBSAVE_USER_PARAM\fP   \fBOD_2700_01\fP"
.br
.ti -1c
.RI "#define \fBRESET_CODE\fP   0xAAAA"
.br
.ti -1c
.RI "#define \fBOD_1F51_02\fP   0x1F51, 0x02 ,ODRegister::SDODataDimension::R1B"
.br
.ti -1c
.RI "#define \fBVMM_DELETE\fP   0x10"
.br
.ti -1c
.RI "#define \fBVMM_INIT\fP   0x11"
.br
.ti -1c
.RI "#define \fBVMM_WRITE\fP   0x12"
.br
.ti -1c
.RI "#define \fBOD_1F50_02\fP   0x1F50, 0x02 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_1F50_02_INIT\fP   0x20"
.br
.ti -1c
.RI "#define \fBOD_1F57_02\fP   0x1F57, 0x02 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_1029_01\fP   0x1029, 0x01 ,ODRegister::SDODataDimension::R1B"
.br
.ti -1c
.RI "#define \fBOD_1029_02\fP   0x1029, 0x02,ODRegister::SDODataDimension::R1B"
.br
.ti -1c
.RI "#define \fBOD_2031_00\fP   0x2031, 0x00, ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2032_00\fP   0x2032, 0x00,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2033_00\fP   0x2033, 0x00,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2034_00\fP   0x2034, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2035_00\fP   0x2035, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2036_00\fP   0x2036, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2037_00\fP   0x2037, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_203B_01\fP   0x203B, 0x01 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_203B_02\fP   0x203B, 0x02 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_203B_03\fP   0x203B, 0x03 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_203B_04\fP   0x203B, 0x04 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_203B_05\fP   0x203B, 0x05 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2056_00\fP   0x2056, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2061_00\fP   0x2061, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2062_00\fP   0x2062, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2063_00\fP   0x2063, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2064_00\fP   0x2064, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2065_00\fP   0x2065, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2066_00\fP   0x2066, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3202_00\fP   0x3202, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_320B_01\fP   0x320B, 0x01 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_320B_02\fP   0x320B, 0x02 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_320B_03\fP   0x320B, 0x03 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_320B_04\fP   0x320B, 0x04 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3210_01\fP   0x3210, 0x01 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3210_02\fP   0x3210, 0x02 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3220_01\fP   0x3220, 0x01 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_3221_00\fP   0x3221, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3240_01\fP   0x3240, 0x01 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3240_02\fP   0x3240, 0x02 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3240_03\fP   0x3240, 0x03 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3240_04\fP   0x3240, 0x04 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3240_05\fP   0x3240, 0x05 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3240_06\fP   0x3240, 0x06 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_60FD_00\fP   0x60FD, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3241_01\fP   0x3241, 0x01 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3241_02\fP   0x3241, 0x02 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3241_03\fP   0x3241, 0x03 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3241_04\fP   0x3241, 0x04 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3250_02\fP   0x3250, 0x02 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3250_03\fP   0x3250, 0x03 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3250_04\fP   0x3250, 0x04 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3250_08\fP   0x3250, 0x08 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_60FE_01\fP   0x60FE, 0x01 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_3700_00\fP   0x3700, 0x00 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_605A_00\fP   0x605A, 0x00 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_605B_00\fP   0x605B, 0x00 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_605C_00\fP   0x605C, 0x00 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_605D_00\fP   0x605D, 0x00 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_605E_00\fP   0x605E, 0x00 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_6041_00\fP   0x6041, 0x00, ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_6041_00_NotReadyToSwitchOn\fP   0x004F,0x0000"
.br
.ti -1c
.RI "#define \fBOD_6041_00_SwitchOnDisabled\fP   0x004F,0x0040"
.br
.ti -1c
.RI "#define \fBOD_6041_00_ReadyToSwitchOn\fP   0x006F,0x0021"
.br
.ti -1c
.RI "#define \fBOD_6041_00_SwitchedOn\fP   0x006F,0x0023"
.br
.ti -1c
.RI "#define \fBOD_6041_00_OperationEnabled\fP   0x006F,0x0027"
.br
.ti -1c
.RI "#define \fBOD_6041_00_QuickStopActive\fP   0x006F,0x0007"
.br
.ti -1c
.RI "#define \fBOD_6041_00_FaultReactionActive\fP   0x004F,0x000F"
.br
.ti -1c
.RI "#define \fBOD_6041_00_Fault\fP   0x004F,0x0008"
.br
.ti -1c
.RI "#define \fBOD_6040_00\fP   0x6040, 0x00, ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_6040_00_SHUTDOWN_MASK\fP   0x0087"
.br
.ti -1c
.RI "#define \fBOD_6040_00_SHUTDOWN_VAL\fP   0x0006"
.br
.ti -1c
.RI "#define \fBOD_6040_00_SWITCHON_MASK\fP   0x008F"
.br
.ti -1c
.RI "#define \fBOD_6040_00_SWITCHON_VAL\fP   0x0007"
.br
.ti -1c
.RI "#define \fBOD_6040_00_ENABLEOP_MASK\fP   0x008F"
.br
.ti -1c
.RI "#define \fBOD_6040_00_ENABLEOP_VAL\fP   0x000F"
.br
.ti -1c
.RI "#define \fBOD_6040_00_DISABLEOP_MASK\fP   0x008F"
.br
.ti -1c
.RI "#define \fBOD_6040_00_DISABLEOP_VAL\fP   0x0007"
.br
.ti -1c
.RI "#define \fBOD_6040_00_QUICKSTOP_MASK\fP   0x0087"
.br
.ti -1c
.RI "#define \fBOD_6040_00_QUICKSTOP_VAL\fP   0x0002"
.br
.ti -1c
.RI "#define \fBOD_6040_00_DISVOLTAGE\fP   0x0082, 0x0000"
.br
.ti -1c
.RI "#define \fBOD_6040_00_RESET_OMS\fP   0x0270, 0x0000"
.br
.ti -1c
.RI "#define \fBOD_6060_00\fP   0x6060, 0x00, ODRegister::SDODataDimension::R1B"
.br
.ti -1c
.RI "#define \fBOD_6060_00_NO_PROFILE\fP   0"
.br
.ti -1c
.RI "#define \fBOD_6060_00_PROFILE_HOMING\fP   6"
.br
.ti -1c
.RI "#define \fBOD_6060_00_PROFILE_POSITIONING\fP   1"
.br
.ti -1c
.RI "#define \fBOD_6064_00\fP   0x6064, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_607A_00\fP   0x607A, 0x00, ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_6065_00\fP   0x6065, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_6066_00\fP   0x6066, 0x00 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_6067_00\fP   0x6067, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_6068_00\fP   0x6068, 0x00 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_607B_01\fP   0x607B, 0x01 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_607B_02\fP   0x607B, 0x02 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_607D_01\fP   0x607D, 0x01 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_607D_02\fP   0x607D, 0x02 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_607E_00\fP   0x607E, 0x00 ,ODRegister::SDODataDimension::R1B"
.br
.ti -1c
.RI "#define \fBOD_6081_00\fP   0x6081, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_6082_00\fP   0x6082, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_6083_00\fP   0x6083, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_6084_00\fP   0x6084, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_6085_00\fP   0x6085, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_60F2_00\fP   0x60F2, 0x00 ,ODRegister::SDODataDimension::R2B"
.br
.ti -1c
.RI "#define \fBOD_608F_01\fP   0x608F, 0x01 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_608F_02\fP   0x608F, 0x02 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_6091_01\fP   0x6091, 0x01 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_6091_02\fP   0x6091, 0x02 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_60C5_00\fP   0x60c5, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_60C6_00\fP   0x60c6, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_6098_00\fP   0x6098, 0x00 ,ODRegister::SDODataDimension::R1B"
.br
.ti -1c
.RI "#define \fBOD_607C_00\fP   0x607C, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_6099_01\fP   0x6099, 0x01 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_6099_02\fP   0x6099, 0x02 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_609A_00\fP   0x609A, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_4013_01\fP   0x4013, 0x01 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2300_00\fP   0x2300, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2301_00\fP   0x2301, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2302_00\fP   0x2302, 0x00 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_4014_01\fP   0x4014, 0x01 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_4014_02\fP   0x4014, 0x02 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_4014_03\fP   0x4014, 0x03 ,ODRegister::SDODataDimension::R4B"
.br
.ti -1c
.RI "#define \fBOD_2500_01\fP   0x2500, 0x01 ,ODRegister::SDODataDimension::R4B"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CONFIG_USER_PARAM   \fBOD_2700_02\fP"

.SS "#define NANOJ_USER_PARAM   \fBOD_2700_03\fP"

.SS "#define OD_1001_00   0x1001, 0x00, ODRegister::SDODataDimension::R1B"

.SS "#define OD_1001_00_COM_ERROR   0x10"

.SS "#define OD_1001_00_GENERAL_ERROR   0x1"

.SS "#define OD_1001_00_I_ERROR   0x2"

.SS "#define OD_1001_00_MANUFACT_ERROR   0x80"

.SS "#define OD_1001_00_PROFILE_ERROR   0x20"

.SS "#define OD_1001_00_RESERVED_ERROR   0x40"

.SS "#define OD_1001_00_TEMP_ERROR   0x8"

.SS "#define OD_1001_00_VOLTAGE_ERROR   0x4"

.SS "#define OD_1003_01   0x1003, 0x01, ODRegister::SDODataDimension::R4B"

.SS "#define OD_1010_01   0x1010, 0x01, ODRegister::SDODataDimension::R4B"

.SS "#define OD_1010_02   0x1010, 0x02, ODRegister::SDODataDimension::R4B"

.SS "#define OD_1010_03   0x1010, 0x03, ODRegister::SDODataDimension::R4B"

.SS "#define OD_1010_04   0x1010, 0x04, ODRegister::SDODataDimension::R4B"

.SS "#define OD_1010_05   0x1010, 0x05, ODRegister::SDODataDimension::R4B"

.SS "#define OD_1010_06   0x1010, 0x06, ODRegister::SDODataDimension::R4B"

.SS "#define OD_1029_01   0x1029, 0x01 ,ODRegister::SDODataDimension::R1B"

.SS "#define OD_1029_02   0x1029, 0x02,ODRegister::SDODataDimension::R1B"

.SS "#define OD_1F50_02   0x1F50, 0x02 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_1F50_02_INIT   0x20"

.SS "#define OD_1F51_02   0x1F51, 0x02 ,ODRegister::SDODataDimension::R1B"

.SS "#define OD_1F57_02   0x1F57, 0x02 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2031_00   0x2031, 0x00, ODRegister::SDODataDimension::R4B"

.SS "#define OD_2032_00   0x2032, 0x00,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2033_00   0x2033, 0x00,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2034_00   0x2034, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2035_00   0x2035, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2036_00   0x2036, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2037_00   0x2037, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_203B_01   0x203B, 0x01 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_203B_02   0x203B, 0x02 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_203B_03   0x203B, 0x03 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_203B_04   0x203B, 0x04 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_203B_05   0x203B, 0x05 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2056_00   0x2056, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2061_00   0x2061, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2062_00   0x2062, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2063_00   0x2063, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2064_00   0x2064, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2065_00   0x2065, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2066_00   0x2066, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2300_00   0x2300, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2301_00   0x2301, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2302_00   0x2302, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2500_01   0x2500, 0x01 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_2700_01   0x2700, 0x01 ,ODRegister::SDODataDimension::R1B"

.SS "#define OD_2700_02   0x2700, 0x02 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_2700_03   0x2700, 0x03 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_2700_04   0x2700, 0x04 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_2700_05   0x2700, 0x05 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_2700_06   0x2700, 0x06 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_2700_07   0x2700, 0x07 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_2700_08   0x2700, 0x08 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_2700_09   0x2700, 0x09 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_3202_00   0x3202, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_320B_01   0x320B, 0x01 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_320B_02   0x320B, 0x02 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_320B_03   0x320B, 0x03 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_320B_04   0x320B, 0x04 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3210_01   0x3210, 0x01 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3210_02   0x3210, 0x02 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3220_01   0x3220, 0x01 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_3221_00   0x3221, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3240_01   0x3240, 0x01 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3240_02   0x3240, 0x02 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3240_03   0x3240, 0x03 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3240_04   0x3240, 0x04 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3240_05   0x3240, 0x05 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3240_06   0x3240, 0x06 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3241_01   0x3241, 0x01 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3241_02   0x3241, 0x02 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3241_03   0x3241, 0x03 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3241_04   0x3241, 0x04 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3250_02   0x3250, 0x02 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3250_03   0x3250, 0x03 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3250_04   0x3250, 0x04 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3250_08   0x3250, 0x08 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_3700_00   0x3700, 0x00 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_4013_01   0x4013, 0x01 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_4014_01   0x4014, 0x01 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_4014_02   0x4014, 0x02 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_4014_03   0x4014, 0x03 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_6040_00   0x6040, 0x00, ODRegister::SDODataDimension::R2B"

.SS "#define OD_6040_00_DISABLEOP_MASK   0x008F"

.SS "#define OD_6040_00_DISABLEOP_VAL   0x0007"

.SS "#define OD_6040_00_DISVOLTAGE   0x0082, 0x0000"

.SS "#define OD_6040_00_ENABLEOP_MASK   0x008F"

.SS "#define OD_6040_00_ENABLEOP_VAL   0x000F"

.SS "#define OD_6040_00_QUICKSTOP_MASK   0x0087"

.SS "#define OD_6040_00_QUICKSTOP_VAL   0x0002"

.SS "#define OD_6040_00_RESET_OMS   0x0270, 0x0000"

.SS "#define OD_6040_00_SHUTDOWN_MASK   0x0087"

.SS "#define OD_6040_00_SHUTDOWN_VAL   0x0006"

.SS "#define OD_6040_00_SWITCHON_MASK   0x008F"

.SS "#define OD_6040_00_SWITCHON_VAL   0x0007"

.SS "#define OD_6041_00   0x6041, 0x00, ODRegister::SDODataDimension::R2B"

.SS "#define OD_6041_00_Fault   0x004F,0x0008"

.SS "#define OD_6041_00_FaultReactionActive   0x004F,0x000F"

.SS "#define OD_6041_00_NotReadyToSwitchOn   0x004F,0x0000"

.SS "#define OD_6041_00_OperationEnabled   0x006F,0x0027"

.SS "#define OD_6041_00_QuickStopActive   0x006F,0x0007"

.SS "#define OD_6041_00_ReadyToSwitchOn   0x006F,0x0021"

.SS "#define OD_6041_00_SwitchedOn   0x006F,0x0023"

.SS "#define OD_6041_00_SwitchOnDisabled   0x004F,0x0040"

.SS "#define OD_605A_00   0x605A, 0x00 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_605B_00   0x605B, 0x00 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_605C_00   0x605C, 0x00 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_605D_00   0x605D, 0x00 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_605E_00   0x605E, 0x00 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_6060_00   0x6060, 0x00, ODRegister::SDODataDimension::R1B"

.SS "#define OD_6060_00_NO_PROFILE   0"

.SS "#define OD_6060_00_PROFILE_HOMING   6"

.SS "#define OD_6060_00_PROFILE_POSITIONING   1"

.SS "#define OD_6064_00   0x6064, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_6065_00   0x6065, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_6066_00   0x6066, 0x00 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_6067_00   0x6067, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_6068_00   0x6068, 0x00 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_607A_00   0x607A, 0x00, ODRegister::SDODataDimension::R4B"

.SS "#define OD_607B_01   0x607B, 0x01 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_607B_02   0x607B, 0x02 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_607C_00   0x607C, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_607D_01   0x607D, 0x01 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_607D_02   0x607D, 0x02 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_607E_00   0x607E, 0x00 ,ODRegister::SDODataDimension::R1B"

.SS "#define OD_6081_00   0x6081, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_6082_00   0x6082, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_6083_00   0x6083, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_6084_00   0x6084, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_6085_00   0x6085, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_608F_01   0x608F, 0x01 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_608F_02   0x608F, 0x02 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_6091_01   0x6091, 0x01 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_6091_02   0x6091, 0x02 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_6098_00   0x6098, 0x00 ,ODRegister::SDODataDimension::R1B"

.SS "#define OD_6099_01   0x6099, 0x01 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_6099_02   0x6099, 0x02 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_609A_00   0x609A, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_60C5_00   0x60c5, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_60C6_00   0x60c6, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_60F2_00   0x60F2, 0x00 ,ODRegister::SDODataDimension::R2B"

.SS "#define OD_60FD_00   0x60FD, 0x00 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_60FE_01   0x60FE, 0x01 ,ODRegister::SDODataDimension::R4B"

.SS "#define OD_SAVE_CODE   0x65766173"

.SS "#define OD_SAVE_DISABLED   0"

.SS "#define OD_SAVE_ENABLED   0x1"

.SS "#define PD4_MOTOR_DI1   0x00010000"

.SS "#define PD4_MOTOR_DI2   0x00020000"

.SS "#define PD4_MOTOR_DI3   0x00040000"

.SS "#define PD4_MOTOR_DI4   0x00080000"

.SS "#define PD4_MOTOR_DI5   0x00100000"

.SS "#define PD4_MOTOR_DI6   0x00200000"

.SS "#define PD4_MOTOR_DO1   0x00010000"

.SS "#define PD4_MOTOR_DO2   0x00020000"

.SS "#define POSITION_SETTING_CTRL_INIT_MASK   0x0370"

.SS "#define POSITION_SETTING_CTRL_INIT_VAL   0x0020"

.SS "#define POSITION_SETTING_START_MASK   0x0370"

.SS "#define POSITION_SETTING_START_VAL   0x0030"

.SS "#define POSITION_TRIGGER_SETTING_CTRL_INIT   0x0370, 0x0000"

.SS "#define RESET_CODE   0xAAAA"

.SS "#define RESET_USER_PARAM   \fBOD_2700_04\fP"

.SS "#define SAVE_USER_PARAM   \fBOD_2700_01\fP"

.SS "#define VMM_DELETE   0x10"

.SS "#define VMM_INIT   0x11"

.SS "#define VMM_WRITE   0x12"

.SS "#define ZERO_SETTING_CTRL_INIT   0x0270,0x0000"

.SS "#define ZERO_SETTING_START   0x0270,0x0010"

.SS "#define ZERO_SETTING_STOP   0x0270,0x0010"

.SS "#define ZERO_STAT_COMPLETED   0x3400,0x1400"

.SS "#define ZERO_STAT_CONFIRMED   0x3400,0x1000"

.SS "#define ZERO_STAT_ERROR_IDL   0x3400,0x2400"

.SS "#define ZERO_STAT_ERROR_RUN   0x3400,0x2000"

.SS "#define ZERO_STAT_INTERRUPTED   0x3400,0x0400"

.SS "#define ZERO_STAT_PERFORMED   0x3400,0x0000"

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
