.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/WINDOWS/ServiceForm.cpp" 3 "Fri Dec 15 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/WINDOWS/ServiceForm.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./AWS/awsProtocol\&.h'\fP
.br
\fC#include 'ServiceForm\&.h'\fP
.br
\fC#include 'ErrorForm\&.h'\fP
.br
\fC#include 'operatingForm\&.h'\fP
.br
\fC#include 'SystemConfig\&.h'\fP
.br
\fC#include 'Notify\&.h'\fP
.br
\fC#include 'PCB301\&.h'\fP
.br
\fC#include 'PCB302\&.h'\fP
.br
\fC#include 'PCB303\&.h'\fP
.br
\fC#include 'PCB304\&.h'\fP
.br
\fC#include 'PCB315\&.h'\fP
.br
\fC#include 'PCB326\&.h'\fP
.br
\fC#include 'VerticalMotor\&.h'\fP
.br
\fC#include 'BodyMotor\&.h'\fP
.br
\fC#include '\&.\&./gantry_global_status\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBACKGROUND\fP   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'ServiceForm\\\\ServiceFormBackground\&.PNG')"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BACKGROUND   Image::FromFile(\fBGantry::applicationResourcePath\fP + 'ServiceForm\\\\ServiceFormBackground\&.PNG')"

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
