.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS/SlideMotor.cpp" 3 "Fri Dec 15 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS/SlideMotor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'SlideMotor\&.h'\fP
.br
\fC#include 'Notify\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGEAR_RATIO\fP   (double) 352\&.2"
.br
.ti -1c
.RI "#define \fBMAX_ROTATION_ANGLE\fP   900"
.br
.ti -1c
.RI "#define \fBMIN_ROTATION_ANGLE\fP   0"
.br
.ti -1c
.RI "#define \fBHOMING_ON_METHOD\fP   19"
.br
.ti -1c
.RI "#define \fBHOMING_OFF_METHOD\fP   20"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GEAR_RATIO   (double) 352\&.2"

.SS "#define HOMING_OFF_METHOD   20"

.SS "#define HOMING_ON_METHOD   19"

.SS "#define MAX_ROTATION_ANGLE   900"

.SS "#define MIN_ROTATION_ANGLE   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
