.TH "SystemConfig" 3 "Thu May 2 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemConfig
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SystemConfig\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "literal System::String ^ \fBFILENAME\fP = 'SystemInit\&.cnf'"
.br
.ti -1c
.RI "literal int \fBFILE_REVISION\fP = 1"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_RUNNING_MODE\fP = 'RUNNING_MODE'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_RUNNING_MODE_COMMENT\fP = '[1=Run, 0=Sim]: tilt, Arm,Body,Vertical,Slide, 301, 302, 303,304,315,326'"
.br
.ti -1c
.RI "literal int \fBPARAM_RUNNING_MODE_TILT\fP = 0"
.br
.ti -1c
.RI "literal int \fBPARAM_RUNNING_MODE_ARM\fP = 1"
.br
.ti -1c
.RI "literal int \fBPARAM_RUNNING_MODE_BODY\fP = 2"
.br
.ti -1c
.RI "literal int \fBPARAM_RUNNING_MODE_VERTICAL\fP = 3"
.br
.ti -1c
.RI "literal int \fBPARAM_RUNNING_MODE_SLIDE\fP = 4"
.br
.ti -1c
.RI "literal int \fBPARAM_RUNNING_MODE_PCB301\fP = 5"
.br
.ti -1c
.RI "literal int \fBPARAM_RUNNING_MODE_PCB302\fP = 6"
.br
.ti -1c
.RI "literal int \fBPARAM_RUNNING_MODE_PCB303\fP = 7"
.br
.ti -1c
.RI "literal int \fBPARAM_RUNNING_MODE_PCB304\fP = 8"
.br
.ti -1c
.RI "literal int \fBPARAM_RUNNING_MODE_PCB315\fP = 9"
.br
.ti -1c
.RI "literal int \fBPARAM_RUNNING_MODE_PCB326\fP = 10"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_RUNNING_MODE_TILT_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_RUNNING_MODE_ARM_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_RUNNING_MODE_BODY_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_RUNNING_MODE_VERTICAL_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_RUNNING_MODE_SLIDE_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_RUNNING_MODE_PCB301_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_RUNNING_MODE_PCB302_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_RUNNING_MODE_PCB303_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_RUNNING_MODE_PCB304_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_RUNNING_MODE_PCB315_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_RUNNING_MODE_PCB326_DEFAULT\fP = '0'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_INSTALLATION_NAME\fP = 'INSTALL_NAME'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_INSTALLATION_NAME_COMMENT\fP = 'Name of the installation'"
.br
.ti -1c
.RI "literal int \fBPARAM_INSTALLATION_NAME_TOP\fP = 0"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_INSTALLATION_NAME_TOP_DEFAULT\fP = 'FACTORY INSTALLATION'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_PACKAGE\fP = 'PACKAGE'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_PACKAGE_COMMENT\fP = 'Package revision set'"
.br
.ti -1c
.RI "literal int \fBPARAM_PACKAGE_ID\fP = 0"
.br
.ti -1c
.RI "literal int \fBPARAM_PACKAGE_FW301\fP = 1"
.br
.ti -1c
.RI "literal int \fBPARAM_PACKAGE_FW302\fP = 2"
.br
.ti -1c
.RI "literal int \fBPARAM_PACKAGE_FW303\fP = 3"
.br
.ti -1c
.RI "literal int \fBPARAM_PACKAGE_FW304\fP = 4"
.br
.ti -1c
.RI "literal int \fBPARAM_PACKAGE_FW315\fP = 5"
.br
.ti -1c
.RI "literal int \fBPARAM_PACKAGE_FW326\fP = 6"
.br
.ti -1c
.RI "literal int \fBPARAM_PACKAGE_FWCAN\fP = 7"
.br
.ti -1c
.RI "literal int \fBPARAM_PACKAGE_FWGEN\fP = 8"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_PACKAGE_ID_DEFAULT\fP = '1\&.0'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_PACKAGE_FW301_DEFAULT\fP = '0\&.1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_PACKAGE_FW302_DEFAULT\fP = '0\&.1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_PACKAGE_FW303_DEFAULT\fP = '0\&.1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_PACKAGE_FW304_DEFAULT\fP = '0\&.1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_PACKAGE_FW315_DEFAULT\fP = '0\&.1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_PACKAGE_FW326_DEFAULT\fP = '0\&.1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_PACKAGE_FWCAN_DEFAULT\fP = '0\&.1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_PACKAGE_FWGEN_DEFAULT\fP = '0\&.1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_AWS_CONNECTIONS\fP = 'AWS_CONNECTION'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_AWS_CONNECTIONS_COMMENT\fP = 'Addresses of the connections with the AWS'"
.br
.ti -1c
.RI "literal int \fBPARAM_AWS_CONNECTIONS_IP\fP = 0"
.br
.ti -1c
.RI "literal int \fBPARAM_AWS_CONNECTIONS_PORT_COMMAND\fP = 1"
.br
.ti -1c
.RI "literal int \fBPARAM_AWS_CONNECTIONS_PORT_EVENTS\fP = 2"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_AWS_CONNECTIONS_IP_DEFAULT\fP = '127\&.0\&.0\&.1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_AWS_CONNECTIONS_PORT_COMMAND_DEFAULT\fP = '10000'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_AWS_CONNECTIONS_PORT_EVENTS_DEFAULT\fP = '10001'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_DEMO_MODE\fP = 'DEMO_MODE'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_DEMO_MODE_COMMENT\fP = 'This is the Demo Mode activation '"
.br
.ti -1c
.RI "literal int \fBPARAM_DEMO_MODE_STATUS\fP = 0"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_DEMO_MODE_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_LOG_DIRECTORY\fP = 'LOG_DIRECTORY'"
.br
.ti -1c
.RI "literal System::String ^ \fBPPARAM_LOG_DIRECTORY_COMMENT\fP = 'The directory reserved for logs '"
.br
.ti -1c
.RI "literal int \fBPARAM_DIR\fP = 0"
.br
.ti -1c
.RI "literal int \fBPARAM_ENA\fP = 1"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_LOG_DIRECTORY_DEFAULT\fP = '\\\\GANTRY_LOGS'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_LOG_ENA_DEFAULT\fP = 'ON'"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBConfigFile\fP ^ \fBConfiguration\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBConfigFile\fP ^ SystemConfig::Configuration\fC [static]\fP"

.SS "literal int SystemConfig::FILE_REVISION = 1"

.SS "literal System::String ^ SystemConfig::FILENAME = 'SystemInit\&.cnf'"

.SS "literal System::String ^ SystemConfig::PARAM_AWS_CONNECTIONS = 'AWS_CONNECTION'"

.SS "literal System::String ^ SystemConfig::PARAM_AWS_CONNECTIONS_COMMENT = 'Addresses of the connections with the AWS'"

.SS "literal int SystemConfig::PARAM_AWS_CONNECTIONS_IP = 0"

.SS "literal System::String ^ SystemConfig::PARAM_AWS_CONNECTIONS_IP_DEFAULT = '127\&.0\&.0\&.1'"

.SS "literal int SystemConfig::PARAM_AWS_CONNECTIONS_PORT_COMMAND = 1"

.SS "literal System::String ^ SystemConfig::PARAM_AWS_CONNECTIONS_PORT_COMMAND_DEFAULT = '10000'"

.SS "literal int SystemConfig::PARAM_AWS_CONNECTIONS_PORT_EVENTS = 2"

.SS "literal System::String ^ SystemConfig::PARAM_AWS_CONNECTIONS_PORT_EVENTS_DEFAULT = '10001'"

.SS "literal System::String ^ SystemConfig::PARAM_DEMO_MODE = 'DEMO_MODE'"

.SS "literal System::String ^ SystemConfig::PARAM_DEMO_MODE_COMMENT = 'This is the Demo Mode activation '"

.SS "literal System::String ^ SystemConfig::PARAM_DEMO_MODE_DEFAULT = '1'"

.SS "literal int SystemConfig::PARAM_DEMO_MODE_STATUS = 0"

.SS "literal int SystemConfig::PARAM_DIR = 0"

.SS "literal int SystemConfig::PARAM_ENA = 1"

.SS "literal System::String ^ SystemConfig::PARAM_INSTALLATION_NAME = 'INSTALL_NAME'"

.SS "literal System::String ^ SystemConfig::PARAM_INSTALLATION_NAME_COMMENT = 'Name of the installation'"

.SS "literal int SystemConfig::PARAM_INSTALLATION_NAME_TOP = 0"

.SS "literal System::String ^ SystemConfig::PARAM_INSTALLATION_NAME_TOP_DEFAULT = 'FACTORY INSTALLATION'"

.SS "literal System::String ^ SystemConfig::PARAM_LOG_DIRECTORY = 'LOG_DIRECTORY'"

.SS "literal System::String ^ SystemConfig::PARAM_LOG_DIRECTORY_DEFAULT = '\\\\GANTRY_LOGS'"

.SS "literal System::String ^ SystemConfig::PARAM_LOG_ENA_DEFAULT = 'ON'"

.SS "literal System::String ^ SystemConfig::PARAM_PACKAGE = 'PACKAGE'"

.SS "literal System::String ^ SystemConfig::PARAM_PACKAGE_COMMENT = 'Package revision set'"

.SS "literal int SystemConfig::PARAM_PACKAGE_FW301 = 1"

.SS "literal System::String ^ SystemConfig::PARAM_PACKAGE_FW301_DEFAULT = '0\&.1'"

.SS "literal int SystemConfig::PARAM_PACKAGE_FW302 = 2"

.SS "literal System::String ^ SystemConfig::PARAM_PACKAGE_FW302_DEFAULT = '0\&.1'"

.SS "literal int SystemConfig::PARAM_PACKAGE_FW303 = 3"

.SS "literal System::String ^ SystemConfig::PARAM_PACKAGE_FW303_DEFAULT = '0\&.1'"

.SS "literal int SystemConfig::PARAM_PACKAGE_FW304 = 4"

.SS "literal System::String ^ SystemConfig::PARAM_PACKAGE_FW304_DEFAULT = '0\&.1'"

.SS "literal int SystemConfig::PARAM_PACKAGE_FW315 = 5"

.SS "literal System::String ^ SystemConfig::PARAM_PACKAGE_FW315_DEFAULT = '0\&.1'"

.SS "literal int SystemConfig::PARAM_PACKAGE_FW326 = 6"

.SS "literal System::String ^ SystemConfig::PARAM_PACKAGE_FW326_DEFAULT = '0\&.1'"

.SS "literal int SystemConfig::PARAM_PACKAGE_FWCAN = 7"

.SS "literal System::String ^ SystemConfig::PARAM_PACKAGE_FWCAN_DEFAULT = '0\&.1'"

.SS "literal int SystemConfig::PARAM_PACKAGE_FWGEN = 8"

.SS "literal System::String ^ SystemConfig::PARAM_PACKAGE_FWGEN_DEFAULT = '0\&.1'"

.SS "literal int SystemConfig::PARAM_PACKAGE_ID = 0"

.SS "literal System::String ^ SystemConfig::PARAM_PACKAGE_ID_DEFAULT = '1\&.0'"

.SS "literal System::String ^ SystemConfig::PARAM_RUNNING_MODE = 'RUNNING_MODE'"

.SS "literal int SystemConfig::PARAM_RUNNING_MODE_ARM = 1"

.SS "literal System::String ^ SystemConfig::PARAM_RUNNING_MODE_ARM_DEFAULT = '1'"

.SS "literal int SystemConfig::PARAM_RUNNING_MODE_BODY = 2"

.SS "literal System::String ^ SystemConfig::PARAM_RUNNING_MODE_BODY_DEFAULT = '1'"

.SS "literal System::String ^ SystemConfig::PARAM_RUNNING_MODE_COMMENT = '[1=Run, 0=Sim]: tilt, Arm,Body,Vertical,Slide, 301, 302, 303,304,315,326'"

.SS "literal int SystemConfig::PARAM_RUNNING_MODE_PCB301 = 5"

.SS "literal System::String ^ SystemConfig::PARAM_RUNNING_MODE_PCB301_DEFAULT = '1'"

.SS "literal int SystemConfig::PARAM_RUNNING_MODE_PCB302 = 6"

.SS "literal System::String ^ SystemConfig::PARAM_RUNNING_MODE_PCB302_DEFAULT = '1'"

.SS "literal int SystemConfig::PARAM_RUNNING_MODE_PCB303 = 7"

.SS "literal System::String ^ SystemConfig::PARAM_RUNNING_MODE_PCB303_DEFAULT = '1'"

.SS "literal int SystemConfig::PARAM_RUNNING_MODE_PCB304 = 8"

.SS "literal System::String ^ SystemConfig::PARAM_RUNNING_MODE_PCB304_DEFAULT = '1'"

.SS "literal int SystemConfig::PARAM_RUNNING_MODE_PCB315 = 9"

.SS "literal System::String ^ SystemConfig::PARAM_RUNNING_MODE_PCB315_DEFAULT = '1'"

.SS "literal int SystemConfig::PARAM_RUNNING_MODE_PCB326 = 10"

.SS "literal System::String ^ SystemConfig::PARAM_RUNNING_MODE_PCB326_DEFAULT = '0'"

.SS "literal int SystemConfig::PARAM_RUNNING_MODE_SLIDE = 4"

.SS "literal System::String ^ SystemConfig::PARAM_RUNNING_MODE_SLIDE_DEFAULT = '1'"

.SS "literal int SystemConfig::PARAM_RUNNING_MODE_TILT = 0"

.SS "literal System::String ^ SystemConfig::PARAM_RUNNING_MODE_TILT_DEFAULT = '1'"

.SS "literal int SystemConfig::PARAM_RUNNING_MODE_VERTICAL = 3"

.SS "literal System::String ^ SystemConfig::PARAM_RUNNING_MODE_VERTICAL_DEFAULT = '1'"

.SS "literal System::String ^ SystemConfig::PPARAM_LOG_DIRECTORY_COMMENT = 'The directory reserved for logs '"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
