.TH "TcpClientCLI" 3 "Fri Dec 15 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TcpClientCLI
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TcpIpClientCLI\&.h>\fP
.PP
Inherited by \fBGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBrxData_slot\fP (cli::array< Byte >^ receiveBuffer, int rc)"
.br
.RI "This is the delegate of the reception handler\&. "
.ti -1c
.RI "delegate void \fBconnection_slot\fP (bool status)"
.br
.RI "This is the delegate of the connection handler\&. "
.ti -1c
.RI "\fBTcpClientCLI\fP (String^ ip, int port)"
.br
.RI "This is the class constructor\&. "
.ti -1c
.RI "void \fBsend\fP (cli::array< Byte >^ buffer)"
.br
.RI "This is function to send data in the BUS\&. "
.ti -1c
.RI "bool \fBisConnected\fP (void)"
.br
.RI "Returns the current connection sattus  "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBthreadWork\fP (void)"
.br
.RI "This is the worker thread for the connection management\&. "
.ti -1c
.RI "virtual void \fBrxData\fP (cli::array< Byte >^ receiveBuffer, int rc)"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "\fBrxData_slot\fP^ \fBrxData_event\fP"
.br
.RI "Reception event\&. "
.ti -1c
.RI "\fBconnection_slot\fP^ \fBconnection_event\fP"
.br
.RI "Connection event\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Thread ^ \fBrunning_thread\fP"
.br
.RI "This is the worker thread handler\&. "
.ti -1c
.RI "Socket ^ \fBclientSocket\fP"
.br
.RI "This is the connected client socket handler\&. "
.ti -1c
.RI "IPAddress ^ \fBserverAddress\fP"
.br
.ti -1c
.RI "IPEndPoint ^ \fBremoteEndpoint\fP"
.br
.ti -1c
.RI "String ^ \fBipserver\fP"
.br
.ti -1c
.RI "int \fBportserver\fP"
.br
.ti -1c
.RI "HANDLE \fBghSemaphore\fP"
.br
.RI "This is the semaphore used to protect the received buffer during the buffer dispatching\&. "
.ti -1c
.RI "bool \fBconnection_status\fP"
.br
.RI "This is the current connection status\&. "
.ti -1c
.RI "cli::array< Byte > ^ \fBrxBuffer\fP"
.br
.RI "This is the reception buffer\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TcpClientCLI::TcpClientCLI (String^ ip, int port)"

.PP
This is the class constructor\&. This is the Class constructor
.PP
The constructor creates all the data necessaries to create the server socket\&.
.PP
After the data initialization the constructor runs the worker thread for the Listening and data reception\&. The thread is self destroying when the program closes\&.
.PP
\fBParameters\fP
.RS 4
\fIip\fP This is a String for the IP address
.br
\fIport\fP This is an integer value for thr server port
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "delegate void TcpClientCLI::connection_slot (bool status)"

.PP
This is the delegate of the connection handler\&. 
.SS "bool TcpClientCLI::isConnected (void)\fC [inline]\fP"

.PP
Returns the current connection sattus  
.PP
\fBReturns\fP
.RS 4
true if the socket is connected 
.RE
.PP

.SS "void TcpClientCLI::rxData (cli::array< Byte >^ receiveBuffer, int rc)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBGenerator\fP\&.
.SS "delegate void TcpClientCLI::rxData_slot (cli::array< Byte >^ receiveBuffer, int rc)"

.PP
This is the delegate of the reception handler\&. 
.SS "void TcpClientCLI::send (cli::array< Byte >^ buffer)"

.PP
This is function to send data in the BUS\&. This function sends a buffer on the bus\&.
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP This is the data buffer to be sent
.RE
.PP

.SS "void TcpClientCLI::threadWork (void)\fC [protected]\fP"

.PP
This is the worker thread for the connection management\&. 
.SH "Member Data Documentation"
.PP 
.SS "Socket ^ TcpClientCLI::clientSocket\fC [private]\fP"

.PP
This is the connected client socket handler\&. 
.SS "bool TcpClientCLI::connection_status\fC [private]\fP"

.PP
This is the current connection status\&. 
.SS "HANDLE TcpClientCLI::ghSemaphore\fC [private]\fP"

.PP
This is the semaphore used to protect the received buffer during the buffer dispatching\&. 
.SS "String ^ TcpClientCLI::ipserver\fC [private]\fP"

.SS "int TcpClientCLI::portserver\fC [private]\fP"

.SS "IPEndPoint ^ TcpClientCLI::remoteEndpoint\fC [private]\fP"

.SS "Thread ^ TcpClientCLI::running_thread\fC [private]\fP"

.PP
This is the worker thread handler\&. 
.SS "cli::array<Byte> ^ TcpClientCLI::rxBuffer\fC [private]\fP"

.PP
This is the reception buffer\&. 
.SS "IPAddress ^ TcpClientCLI::serverAddress\fC [private]\fP"

.SH "Event Documentation"
.PP 
.SS "\fBconnection_slot\fP^ TcpClientCLI::connection_event"

.PP
Connection event\&. 
.SS "\fBrxData_slot\fP^ TcpClientCLI::rxData_event"

.PP
Reception event\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
