.TH "C:/Users/marco/OneDrive/Documenti/Visual Studio 2022/Projects/MCPU/MCPU_MASTER/TcpIpServerCLI.h" 3MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/marco/OneDrive/Documenti/Visual Studio 2022/Projects/MCPU/MCPU_MASTER/TcpIpServerCLI.h
.SH SYNOPSIS
.br
.PP
\fC#include <windows\&.h>\fP
.br
\fC#include 'winuser\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTcpIpServerCLI\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWIN32_LEAN_AND_MEAN\fP"
.br
.ti -1c
.RI "#define \fBTcpIpServerCLI_DISPATCH_MESSAGE\fP   (WM_USER + 1)"
.br
.ti -1c
.RI "#define \fBTcpIpServerCLI_DISCONNECTION_MESSAGE\fP   (WM_USER + 2)"
.br
.ti -1c
.RI "#define \fBTcpIpServerCLI_CONNECTION_MESSAGE\fP   (WM_USER + 3)"
.br
.ti -1c
.RI "#define \fBTcpIpServerCLI_RX_BUFFER_SIZE\fP   (4096)"
.br
.ti -1c
.RI "#define \fBTcpIpServerCLI_TX_BUFFER_SIZE\fP   (4096)"
.br
.ti -1c
.RI "#define \fBTcpIpServerCLI_DISPATCH_BUFFER_SIZE\fP   (100)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TcpIpServerCLI_CONNECTION_MESSAGE   (WM_USER + 3)"

.SS "#define TcpIpServerCLI_DISCONNECTION_MESSAGE   (WM_USER + 2)"

.SS "#define TcpIpServerCLI_DISPATCH_BUFFER_SIZE   (100)"

.SS "#define TcpIpServerCLI_DISPATCH_MESSAGE   (WM_USER + 1)"

.SS "#define TcpIpServerCLI_RX_BUFFER_SIZE   (4096)"

.SS "#define TcpIpServerCLI_TX_BUFFER_SIZE   (4096)"

.SS "#define WIN32_LEAN_AND_MEAN"

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
