.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/GENERATOR/TcpIpClientCLI.h" 3 "Mon Dec 4 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/GENERATOR/TcpIpClientCLI.h
.SH SYNOPSIS
.br
.PP
\fC#include <windows\&.h>\fP
.br
\fC#include 'winuser\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTcpClientCLI\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWIN32_LEAN_AND_MEAN\fP"
.br
.ti -1c
.RI "#define \fBTcpClientCLI_DISPATCH_MESSAGE\fP   (WM_USER + 1)"
.br
.ti -1c
.RI "#define \fBTcpClientCLI_DISCONNECTION_MESSAGE\fP   (WM_USER + 2)"
.br
.ti -1c
.RI "#define \fBTcpClientCLI_CONNECTION_MESSAGE\fP   (WM_USER + 3)"
.br
.ti -1c
.RI "#define \fBTcpClientCLI_RX_BUFFER_SIZE\fP   (4096)"
.br
.ti -1c
.RI "#define \fBTcpClientCLI_TX_BUFFER_SIZE\fP   (4096)"
.br
.ti -1c
.RI "#define \fBTcpClientCLI_DISPATCH_BUFFER_SIZE\fP   (100)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TcpClientCLI_CONNECTION_MESSAGE   (WM_USER + 3)"

.SS "#define TcpClientCLI_DISCONNECTION_MESSAGE   (WM_USER + 2)"

.SS "#define TcpClientCLI_DISPATCH_BUFFER_SIZE   (100)"

.SS "#define TcpClientCLI_DISPATCH_MESSAGE   (WM_USER + 1)"

.SS "#define TcpClientCLI_RX_BUFFER_SIZE   (4096)"

.SS "#define TcpClientCLI_TX_BUFFER_SIZE   (4096)"

.SS "#define WIN32_LEAN_AND_MEAN"

.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
