.TH "C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS/TiltMotor.h" 3 "Mon May 13 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/m.rispoli/Documents/Workspace/Git/mcpu_master_vs/PROJECT_VB/MCPU/MCPU_MASTER/MOTORS/TiltMotor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ExposureModule\&.h'\fP
.br
\fC#include 'CalibrationConfig\&.h'\fP
.br
\fC#include 'CanOpenMotor\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTiltMotor\fP"
.br
.RI "This is the Tilt Module class implementation"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
