.TH "TomoConfig" 3 "Thu May 2 2024" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TomoConfig
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CalibrationConfig\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBtomo_id\fP { \fBTOMO1F_NARROW\fP = 0, \fBTOMO1F_INTERMEDIATE\fP, \fBTOMO1F_WIDE\fP, \fBTOMO2F_NARROW\fP, \fBTOMO2F_INTERMEDIATE\fP, \fBTOMO2F_WIDE\fP, \fBTOMO3F_NARROW\fP, \fBTOMO3F_INTERMEDIATE\fP, \fBTOMO3F_WIDE\fP, \fBTOMO4F_NARROW\fP, \fBTOMO4F_INTERMEDIATE\fP, \fBTOMO4F_WIDE\fP, \fBTOMO5F_NARROW\fP, \fBTOMO5F_INTERMEDIATE\fP, \fBTOMO5F_WIDE\fP, \fBTOMO_ID_NUM\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "literal System::String ^ \fBFILENAME\fP = 'TomoConfig\&.cnf'"
.br
.ti -1c
.RI "literal int \fBFILE_REVISION\fP = 1"
.br
.ti -1c
.RI "literal int \fBPARAM_TOMO_HOME\fP = 0"
.br
.ti -1c
.RI "literal int \fBPARAM_TOMO_END\fP = 1"
.br
.ti -1c
.RI "literal int \fBPARAM_TOMO_FPS\fP = 2"
.br
.ti -1c
.RI "literal int \fBPARAM_TOMO_SAMPLES\fP = 3"
.br
.ti -1c
.RI "literal int \fBPARAM_TOMO_SKIP\fP = 4"
.br
.ti -1c
.RI "literal int \fBPARAM_TOMO_SPEED\fP = 5"
.br
.ti -1c
.RI "literal int \fBPARAM_TOMO_ACC\fP = 6"
.br
.ti -1c
.RI "literal int \fBPARAM_TOMO_DEC\fP = 7"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_NARROW\fP = 'TOMO1F_NARROW'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_NARROW_COMMENT\fP = 'Defines the Tomo 1F NARROW configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_NARROW_HOME_DEFAULT\fP = '825'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_NARROW_END_DEFAULT\fP = '\-825'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_NARROW_FPS_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_NARROW_SAMPLES_DEFAULT\fP = '11'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_NARROW_SKIP_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_NARROW_SPEED_DEFAULT\fP = '150'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_NARROW_ACC_DEFAULT\fP = '150'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_NARROW_DEC_DEFAULT\fP = '150'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_INTERMEDIATE\fP = 'TOMO1F_INTERMEDIATE'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_INTERMEDIATE_COMMENT\fP = 'Defines the Tomo 1F INTERMEDIATE configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_INTERMEDIATE_HOME_DEFAULT\fP = '1300'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_INTERMEDIATE_END_DEFAULT\fP = '\-1300'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_INTERMEDIATE_FPS_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_INTERMEDIATE_SAMPLES_DEFAULT\fP = '13'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_INTERMEDIATE_SKIP_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_INTERMEDIATE_SPEED_DEFAULT\fP = '200'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_INTERMEDIATE_ACC_DEFAULT\fP = '200'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_INTERMEDIATE_DEC_DEFAULT\fP = '200'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_WIDE\fP = 'TOMO1F_WIDE'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_WIDE_COMMENT\fP = 'Defines the Tomo 1F WIDE configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_WIDE_HOME_DEFAULT\fP = '1900'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_WIDE_END_DEFAULT\fP = '\-1900'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_WIDE_FPS_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_WIDE_SAMPLES_DEFAULT\fP = '19'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_WIDE_SKIP_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_WIDE_SPEED_DEFAULT\fP = '200'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_WIDE_ACC_DEFAULT\fP = '200'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO1F_WIDE_DEC_DEFAULT\fP = '200'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_NARROW\fP = 'TOMO2F_NARROW'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_NARROW_COMMENT\fP = 'Defines the Tomo 2F NARROW configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_NARROW_HOME_DEFAULT\fP = '825'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_NARROW_END_DEFAULT\fP = '\-825'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_NARROW_FPS_DEFAULT\fP = '2'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_NARROW_SAMPLES_DEFAULT\fP = '11'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_NARROW_SKIP_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_NARROW_SPEED_DEFAULT\fP = '300'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_NARROW_ACC_DEFAULT\fP = '600'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_NARROW_DEC_DEFAULT\fP = '600'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_INTERMEDIATE\fP = 'TOMO2F_INTERMEDIATE'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_INTERMEDIATE_COMMENT\fP = 'Defines the Tomo 2F INTERMEDIATE configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_INTERMEDIATE_HOME_DEFAULT\fP = '1300'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_INTERMEDIATE_END_DEFAULT\fP = '\-1300'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_INTERMEDIATE_FPS_DEFAULT\fP = '2'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_INTERMEDIATE_SAMPLES_DEFAULT\fP = '13'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_INTERMEDIATE_SKIP_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_INTERMEDIATE_SPEED_DEFAULT\fP = '400'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_INTERMEDIATE_ACC_DEFAULT\fP = '800'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_INTERMEDIATE_DEC_DEFAULT\fP = '800'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_WIDE\fP = 'TOMO2F_WIDE'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_WIDE_COMMENT\fP = 'Defines the Tomo 2F WIDE configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_WIDE_HOME_DEFAULT\fP = '1900'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_WIDE_END_DEFAULT\fP = '\-1900'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_WIDE_FPS_DEFAULT\fP = '2'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_WIDE_SAMPLES_DEFAULT\fP = '19'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_WIDE_SKIP_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_WIDE_SPEED_DEFAULT\fP = '400'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_WIDE_ACC_DEFAULT\fP = '800'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO2F_WIDE_DEC_DEFAULT\fP = '800'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_NARROW\fP = 'TOMO3F_NARROW'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_NARROW_COMMENT\fP = 'Defines the Tomo 3F NARROW configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_NARROW_HOME_DEFAULT\fP = '825'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_NARROW_END_DEFAULT\fP = '\-825'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_NARROW_FPS_DEFAULT\fP = '2'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_NARROW_SAMPLES_DEFAULT\fP = '11'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_NARROW_SKIP_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_NARROW_SPEED_DEFAULT\fP = '300'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_NARROW_ACC_DEFAULT\fP = '600'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_NARROW_DEC_DEFAULT\fP = '600'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_INTERMEDIATE\fP = 'TOMO3F_INTERMEDIATE'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_INTERMEDIATE_COMMENT\fP = 'Defines the Tomo 3F INTERMEDIATE configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_INTERMEDIATE_HOME_DEFAULT\fP = '1300'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_INTERMEDIATE_END_DEFAULT\fP = '\-1300'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_INTERMEDIATE_FPS_DEFAULT\fP = '2'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_INTERMEDIATE_SAMPLES_DEFAULT\fP = '13'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_INTERMEDIATE_SKIP_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_INTERMEDIATE_SPEED_DEFAULT\fP = '400'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_INTERMEDIATE_ACC_DEFAULT\fP = '800'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_INTERMEDIATE_DEC_DEFAULT\fP = '800'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_WIDE\fP = 'TOMO3F_WIDE'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_WIDE_COMMENT\fP = 'Defines the Tomo 3F WIDE configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_WIDE_HOME_DEFAULT\fP = '2608'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_WIDE_END_DEFAULT\fP = '\-2608'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_WIDE_FPS_DEFAULT\fP = '2'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_WIDE_SAMPLES_DEFAULT\fP = '24'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_WIDE_SKIP_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_WIDE_SPEED_DEFAULT\fP = '435'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_WIDE_ACC_DEFAULT\fP = '869'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO3F_WIDE_DEC_DEFAULT\fP = '869'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_NARROW\fP = 'TOMO4F_NARROW'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_NARROW_COMMENT\fP = 'Defines the Tomo 4F NARROW configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_NARROW_HOME_DEFAULT\fP = '975'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_NARROW_END_DEFAULT\fP = '\-975'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_NARROW_FPS_DEFAULT\fP = '4'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_NARROW_SAMPLES_DEFAULT\fP = '11'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_NARROW_SKIP_DEFAULT\fP = '3'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_NARROW_SPEED_DEFAULT\fP = '600'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_NARROW_ACC_DEFAULT\fP = '800'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_NARROW_DEC_DEFAULT\fP = '800'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_INTERMEDIATE\fP = 'TOMO4F_INTERMEDIATE'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_INTERMEDIATE_COMMENT\fP = 'Defines the Tomo 4F INTERMEDIATE configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_INTERMEDIATE_HOME_DEFAULT\fP = '1500'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_INTERMEDIATE_END_DEFAULT\fP = '\-1500'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_INTERMEDIATE_FPS_DEFAULT\fP = '3'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_INTERMEDIATE_SAMPLES_DEFAULT\fP = '13'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_INTERMEDIATE_SKIP_DEFAULT\fP = '3'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_INTERMEDIATE_SPEED_DEFAULT\fP = '600'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_INTERMEDIATE_ACC_DEFAULT\fP = '600'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_INTERMEDIATE_DEC_DEFAULT\fP = '600'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_WIDE\fP = 'TOMO4F_WIDE'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_WIDE_COMMENT\fP = 'Defines the Tomo 4F WIDE configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_WIDE_HOME_DEFAULT\fP = '2550'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_WIDE_END_DEFAULT\fP = '\-2550'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_WIDE_FPS_DEFAULT\fP = '3'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_WIDE_SAMPLES_DEFAULT\fP = '24'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_WIDE_SKIP_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_WIDE_SPEED_DEFAULT\fP = '675'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_WIDE_ACC_DEFAULT\fP = '900'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO4F_WIDE_DEC_DEFAULT\fP = '900'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_NARROW\fP = 'TOMO5F_NARROW'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_NARROW_COMMENT\fP = 'Defines the Tomo 5F NARROW configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_NARROW_HOME_DEFAULT\fP = '825'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_NARROW_END_DEFAULT\fP = '\-825'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_NARROW_FPS_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_NARROW_SAMPLES_DEFAULT\fP = '11'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_NARROW_SKIP_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_NARROW_SPEED_DEFAULT\fP = '150'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_NARROW_ACC_DEFAULT\fP = '150'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_NARROW_DEC_DEFAULT\fP = '150'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_INTERMEDIATE\fP = 'TOMO5F_INTERMEDIATE'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_INTERMEDIATE_COMMENT\fP = 'Defines the Tomo 5F INTERMEDIATE configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_INTERMEDIATE_HOME_DEFAULT\fP = '1300'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_INTERMEDIATE_END_DEFAULT\fP = '\-1300'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_INTERMEDIATE_FPS_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_INTERMEDIATE_SAMPLES_DEFAULT\fP = '13'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_INTERMEDIATE_SKIP_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_INTERMEDIATE_SPEED_DEFAULT\fP = '200'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_INTERMEDIATE_ACC_DEFAULT\fP = '200'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_INTERMEDIATE_DEC_DEFAULT\fP = '200'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_WIDE\fP = 'TOMO5F_WIDE'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_WIDE_COMMENT\fP = 'Defines the Tomo 5F WIDE configuration'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_WIDE_HOME_DEFAULT\fP = '2609'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_WIDE_END_DEFAULT\fP = '\-2609'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_WIDE_FPS_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_WIDE_SAMPLES_DEFAULT\fP = '24'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_WIDE_SKIP_DEFAULT\fP = '1'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_WIDE_SPEED_DEFAULT\fP = '217'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_WIDE_ACC_DEFAULT\fP = '217'"
.br
.ti -1c
.RI "literal System::String ^ \fBPARAM_TOMO5F_WIDE_DEC_DEFAULT\fP = '217'"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBConfigFile\fP ^ \fBConfiguration\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum class \fBTomoConfig::tomo_id\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITOMO1F_NARROW \fP\fP
.TP
\fB\fITOMO1F_INTERMEDIATE \fP\fP
.TP
\fB\fITOMO1F_WIDE \fP\fP
.TP
\fB\fITOMO2F_NARROW \fP\fP
.TP
\fB\fITOMO2F_INTERMEDIATE \fP\fP
.TP
\fB\fITOMO2F_WIDE \fP\fP
.TP
\fB\fITOMO3F_NARROW \fP\fP
.TP
\fB\fITOMO3F_INTERMEDIATE \fP\fP
.TP
\fB\fITOMO3F_WIDE \fP\fP
.TP
\fB\fITOMO4F_NARROW \fP\fP
.TP
\fB\fITOMO4F_INTERMEDIATE \fP\fP
.TP
\fB\fITOMO4F_WIDE \fP\fP
.TP
\fB\fITOMO5F_NARROW \fP\fP
.TP
\fB\fITOMO5F_INTERMEDIATE \fP\fP
.TP
\fB\fITOMO5F_WIDE \fP\fP
.TP
\fB\fITOMO_ID_NUM \fP\fP
.SH "Member Data Documentation"
.PP 
.SS "\fBConfigFile\fP ^ TomoConfig::Configuration\fC [static]\fP"

.SS "literal int TomoConfig::FILE_REVISION = 1"

.SS "literal System::String ^ TomoConfig::FILENAME = 'TomoConfig\&.cnf'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_INTERMEDIATE = 'TOMO1F_INTERMEDIATE'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_INTERMEDIATE_ACC_DEFAULT = '200'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_INTERMEDIATE_COMMENT = 'Defines the Tomo 1F INTERMEDIATE configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_INTERMEDIATE_DEC_DEFAULT = '200'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_INTERMEDIATE_END_DEFAULT = '\-1300'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_INTERMEDIATE_FPS_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_INTERMEDIATE_HOME_DEFAULT = '1300'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_INTERMEDIATE_SAMPLES_DEFAULT = '13'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_INTERMEDIATE_SKIP_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_INTERMEDIATE_SPEED_DEFAULT = '200'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_NARROW = 'TOMO1F_NARROW'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_NARROW_ACC_DEFAULT = '150'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_NARROW_COMMENT = 'Defines the Tomo 1F NARROW configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_NARROW_DEC_DEFAULT = '150'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_NARROW_END_DEFAULT = '\-825'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_NARROW_FPS_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_NARROW_HOME_DEFAULT = '825'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_NARROW_SAMPLES_DEFAULT = '11'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_NARROW_SKIP_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_NARROW_SPEED_DEFAULT = '150'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_WIDE = 'TOMO1F_WIDE'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_WIDE_ACC_DEFAULT = '200'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_WIDE_COMMENT = 'Defines the Tomo 1F WIDE configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_WIDE_DEC_DEFAULT = '200'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_WIDE_END_DEFAULT = '\-1900'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_WIDE_FPS_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_WIDE_HOME_DEFAULT = '1900'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_WIDE_SAMPLES_DEFAULT = '19'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_WIDE_SKIP_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO1F_WIDE_SPEED_DEFAULT = '200'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_INTERMEDIATE = 'TOMO2F_INTERMEDIATE'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_INTERMEDIATE_ACC_DEFAULT = '800'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_INTERMEDIATE_COMMENT = 'Defines the Tomo 2F INTERMEDIATE configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_INTERMEDIATE_DEC_DEFAULT = '800'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_INTERMEDIATE_END_DEFAULT = '\-1300'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_INTERMEDIATE_FPS_DEFAULT = '2'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_INTERMEDIATE_HOME_DEFAULT = '1300'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_INTERMEDIATE_SAMPLES_DEFAULT = '13'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_INTERMEDIATE_SKIP_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_INTERMEDIATE_SPEED_DEFAULT = '400'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_NARROW = 'TOMO2F_NARROW'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_NARROW_ACC_DEFAULT = '600'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_NARROW_COMMENT = 'Defines the Tomo 2F NARROW configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_NARROW_DEC_DEFAULT = '600'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_NARROW_END_DEFAULT = '\-825'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_NARROW_FPS_DEFAULT = '2'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_NARROW_HOME_DEFAULT = '825'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_NARROW_SAMPLES_DEFAULT = '11'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_NARROW_SKIP_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_NARROW_SPEED_DEFAULT = '300'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_WIDE = 'TOMO2F_WIDE'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_WIDE_ACC_DEFAULT = '800'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_WIDE_COMMENT = 'Defines the Tomo 2F WIDE configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_WIDE_DEC_DEFAULT = '800'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_WIDE_END_DEFAULT = '\-1900'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_WIDE_FPS_DEFAULT = '2'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_WIDE_HOME_DEFAULT = '1900'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_WIDE_SAMPLES_DEFAULT = '19'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_WIDE_SKIP_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO2F_WIDE_SPEED_DEFAULT = '400'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_INTERMEDIATE = 'TOMO3F_INTERMEDIATE'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_INTERMEDIATE_ACC_DEFAULT = '800'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_INTERMEDIATE_COMMENT = 'Defines the Tomo 3F INTERMEDIATE configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_INTERMEDIATE_DEC_DEFAULT = '800'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_INTERMEDIATE_END_DEFAULT = '\-1300'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_INTERMEDIATE_FPS_DEFAULT = '2'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_INTERMEDIATE_HOME_DEFAULT = '1300'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_INTERMEDIATE_SAMPLES_DEFAULT = '13'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_INTERMEDIATE_SKIP_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_INTERMEDIATE_SPEED_DEFAULT = '400'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_NARROW = 'TOMO3F_NARROW'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_NARROW_ACC_DEFAULT = '600'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_NARROW_COMMENT = 'Defines the Tomo 3F NARROW configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_NARROW_DEC_DEFAULT = '600'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_NARROW_END_DEFAULT = '\-825'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_NARROW_FPS_DEFAULT = '2'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_NARROW_HOME_DEFAULT = '825'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_NARROW_SAMPLES_DEFAULT = '11'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_NARROW_SKIP_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_NARROW_SPEED_DEFAULT = '300'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_WIDE = 'TOMO3F_WIDE'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_WIDE_ACC_DEFAULT = '869'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_WIDE_COMMENT = 'Defines the Tomo 3F WIDE configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_WIDE_DEC_DEFAULT = '869'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_WIDE_END_DEFAULT = '\-2608'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_WIDE_FPS_DEFAULT = '2'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_WIDE_HOME_DEFAULT = '2608'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_WIDE_SAMPLES_DEFAULT = '24'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_WIDE_SKIP_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO3F_WIDE_SPEED_DEFAULT = '435'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_INTERMEDIATE = 'TOMO4F_INTERMEDIATE'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_INTERMEDIATE_ACC_DEFAULT = '600'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_INTERMEDIATE_COMMENT = 'Defines the Tomo 4F INTERMEDIATE configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_INTERMEDIATE_DEC_DEFAULT = '600'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_INTERMEDIATE_END_DEFAULT = '\-1500'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_INTERMEDIATE_FPS_DEFAULT = '3'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_INTERMEDIATE_HOME_DEFAULT = '1500'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_INTERMEDIATE_SAMPLES_DEFAULT = '13'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_INTERMEDIATE_SKIP_DEFAULT = '3'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_INTERMEDIATE_SPEED_DEFAULT = '600'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_NARROW = 'TOMO4F_NARROW'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_NARROW_ACC_DEFAULT = '800'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_NARROW_COMMENT = 'Defines the Tomo 4F NARROW configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_NARROW_DEC_DEFAULT = '800'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_NARROW_END_DEFAULT = '\-975'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_NARROW_FPS_DEFAULT = '4'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_NARROW_HOME_DEFAULT = '975'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_NARROW_SAMPLES_DEFAULT = '11'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_NARROW_SKIP_DEFAULT = '3'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_NARROW_SPEED_DEFAULT = '600'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_WIDE = 'TOMO4F_WIDE'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_WIDE_ACC_DEFAULT = '900'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_WIDE_COMMENT = 'Defines the Tomo 4F WIDE configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_WIDE_DEC_DEFAULT = '900'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_WIDE_END_DEFAULT = '\-2550'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_WIDE_FPS_DEFAULT = '3'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_WIDE_HOME_DEFAULT = '2550'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_WIDE_SAMPLES_DEFAULT = '24'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_WIDE_SKIP_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO4F_WIDE_SPEED_DEFAULT = '675'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_INTERMEDIATE = 'TOMO5F_INTERMEDIATE'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_INTERMEDIATE_ACC_DEFAULT = '200'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_INTERMEDIATE_COMMENT = 'Defines the Tomo 5F INTERMEDIATE configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_INTERMEDIATE_DEC_DEFAULT = '200'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_INTERMEDIATE_END_DEFAULT = '\-1300'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_INTERMEDIATE_FPS_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_INTERMEDIATE_HOME_DEFAULT = '1300'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_INTERMEDIATE_SAMPLES_DEFAULT = '13'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_INTERMEDIATE_SKIP_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_INTERMEDIATE_SPEED_DEFAULT = '200'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_NARROW = 'TOMO5F_NARROW'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_NARROW_ACC_DEFAULT = '150'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_NARROW_COMMENT = 'Defines the Tomo 5F NARROW configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_NARROW_DEC_DEFAULT = '150'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_NARROW_END_DEFAULT = '\-825'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_NARROW_FPS_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_NARROW_HOME_DEFAULT = '825'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_NARROW_SAMPLES_DEFAULT = '11'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_NARROW_SKIP_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_NARROW_SPEED_DEFAULT = '150'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_WIDE = 'TOMO5F_WIDE'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_WIDE_ACC_DEFAULT = '217'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_WIDE_COMMENT = 'Defines the Tomo 5F WIDE configuration'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_WIDE_DEC_DEFAULT = '217'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_WIDE_END_DEFAULT = '\-2609'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_WIDE_FPS_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_WIDE_HOME_DEFAULT = '2609'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_WIDE_SAMPLES_DEFAULT = '24'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_WIDE_SKIP_DEFAULT = '1'"

.SS "literal System::String ^ TomoConfig::PARAM_TOMO5F_WIDE_SPEED_DEFAULT = '217'"

.SS "literal int TomoConfig::PARAM_TOMO_ACC = 6"

.SS "literal int TomoConfig::PARAM_TOMO_DEC = 7"

.SS "literal int TomoConfig::PARAM_TOMO_END = 1"

.SS "literal int TomoConfig::PARAM_TOMO_FPS = 2"

.SS "literal int TomoConfig::PARAM_TOMO_HOME = 0"

.SS "literal int TomoConfig::PARAM_TOMO_SAMPLES = 3"

.SS "literal int TomoConfig::PARAM_TOMO_SKIP = 4"

.SS "literal int TomoConfig::PARAM_TOMO_SPEED = 5"


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
