.TH "awsModule" 3 "Mon Jul 24 2023" "MCPU_MASTER Software Description" \" -*- nroff -*-
.ad l
.nh
.SH NAME
awsModule \- AWS Interface Module
.PP
 \- This is the module implementing the communication protocol with the AWS\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBAWS Protocol Api\fP"
.br
.ti -1c
.RI "\fBAWS Protocol Command set\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBawsProtocol\fP"
.br
.RI "This is the class implementing the AWS Interface Module "
.in -1c
.SH "Detailed Description"
.PP 
This is the module implementing the communication protocol with the AWS\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for MCPU_MASTER Software Description from the source code\&.
